### ISSUE TITLE
544307D1 - DEAD OR ALIVE 4

### ISSUE THREAD

**Issue by sephiroth99** [xenia-project/game-compatibility#146]
[Marketplace](http://marketplace.xbox.com/en-CA/Product/DEAD-OR-ALIVE-4/66acd000-77fe-1000-9115-d802544307d1)

Tested with benvanik/xenia@76efd13

[Log](https://gist.github.com/sephiroth99/b35d91e06f1d6b2b33a0)

Game crash:
```
Unhandled exception at 0x00000000A0034988 in xenia.exe: 0xC0000005: Access violation reading location 0x0000000007000000.
```
Call stack looks like this:
```
 	00000000a0034988()	Unknown
 	00000000a1550713()	Unknown
 	00000000a154dbe3()	Unknown
 	00000000a154cd30()	Unknown
 	00000000a15432fc()	Unknown
 	00000000a154269f()	Unknown
 	00000000a1542538()	Unknown
 	00000000a1542309()	Unknown
 	00000000a154083e()	Unknown
 	00000000a153e8f3()	Unknown
 	00000000a153c088()	Unknown
 	00000000a0c54a3c()	Unknown
 	00000000a0000dc7()	Unknown
 	00000000a000004b()	Unknown
>	xenia.exe!xe::cpu::backend::x64::X64Function::CallImpl(xe::cpu::ThreadState * thread_state, unsigned int return_address) Line 39	C++
 	xenia.exe!xe::cpu::GuestFunction::Call(xe::cpu::ThreadState * thread_state, unsigned int return_address) Line 123	C++
 	xenia.exe!xe::cpu::Processor::Execute(xe::cpu::ThreadState * thread_state, unsigned int address) Line 307	C++
 	xenia.exe!xe::cpu::Processor::Execute(xe::cpu::ThreadState * thread_state, unsigned int address, unsigned __int64 * args, unsigned __int64 arg_count) Line 324	C++
 	xenia.exe!xe::kernel::XThread::Execute() Line 427	C++
 	xenia.exe!xe::kernel::XThread::Create::__l2::<lambda>() Line 310	C++
 	[External Code]	
 	xenia.exe!xe::threading::ThreadStartRoutine(void * parameter) Line 435	C++
 	[External Code]	
```

state-nothing

**Comment by theoldsport** [comment]
Dead or Alive 4 gets ingame now :) You can't see much, but I did win one match blind.

![doa4](https://cloud.githubusercontent.com/assets/13494133/16214124/1a94af96-370a-11e6-81b7-ff920c8e778d.png)

state-gameplay, gpu-missing-drawing or gpu-corrupt-drawing

**Comment by twrist** [comment]
In-game is now full of vertex explosion goodness, it crashed when i jumped at one point
![1544962587](https://user-images.githubusercontent.com/670020/50053424-bd462800-016f-11e9-9be0-c1391eff57a4.png)
![1544962617](https://user-images.githubusercontent.com/670020/50053426-c505cc80-016f-11e9-8df5-c49f1a58646f.png)
```
!> 00000028 ResolvePath(\Device\Harddisk0\) failed - no root found
!> 00000028 Unimplemented XLIVEBASE message app=000000FC, msg=00058037, arg1=0006E000, arg2=4018F9C0
!> 00000028 BaseHeap::Release failed because address is not a region start
!> 00000028 PhysicalHeap::Release failed due to parent heap failure
!> 000001A0 BaseHeap::Protect failed due to uncommitted page
...
```


[xenia.log](https://cdn.discordapp.com/attachments/308207592482668545/523836559573778432/xenia.zip)

**Comment by tabnk** [comment]
Tested on latest DX12 build. Appears to have same issue as above.

**Comment by KBouder** [comment]
Would you look at that! Some progress has been made!
![image](https://user-images.githubusercontent.com/11525691/68738117-7ba64300-05b3-11ea-8a1a-8d9f41746315.png)

I am unable to upload the log (It's 700MB)

Specs:
Nvidia RTX 2070
Ryzen 7 2700X 3.6GHz
16 GB Ram

**Comment by tabnk** [comment]
Tested on latest build. 

There's been an issue reading content from the game disc. This is likely caused by bad or unimplemented file IO calls.

**Comment by Margen67** [comment]
@tabnk You need to provide the commit hash and a log.

**Comment by tabnk** [comment]
Dead or Alive 4.

commit hash https://github.com/xenia-project/xenia/commit/cf0251cd9f57669320a0ddf774d7b92fd800d0bb

[xenia.log](https://github.com/xenia-project/game-compatibility/files/4506874/xenia.log)

**Comment by Hadocem** [comment]
The game stops at MENU.

![DDDDDybvg556juh](https://user-images.githubusercontent.com/28853392/81479962-f667b800-91fc-11ea-810e-eefb5b3a0d93.png)

[xenia.log](https://github.com/xenia-project/game-compatibility/files/4604139/xenia.log)

**Comment by Etokapa** [comment]
Tested on https://github.com/xenia-project/xenia/commit/c3d48eb2fa2e43a19716b52fa5e545f643486b6b

Played 1 round. Solid 60FPS. Xenia closed after returning to the title screen.

• You must set `--d3d12_resolution_scale=2`!
• Minor graphical issues with vertex explosions and corrupted textures. Press F5 to fix.
• Major graphical issues with textures not rendering on parts of 3D models.

![do (1)](https://user-images.githubusercontent.com/31154606/100653866-a1ad9b00-330e-11eb-9199-01ca19675f20.png)
![do (2)](https://user-images.githubusercontent.com/31154606/100653869-a2463180-330e-11eb-847d-522a6a3d21de.png)

[xenia.zip](https://github.com/xenia-project/game-compatibility/files/5618218/xenia.zip)

state-gameplay

**Comment by 0Sayuku0** [comment]
The game is crashing on the menu in the latest xenia builds.

**Comment by 0Sayuku0** [comment]
A little update, I figured out a way so it won't crash on the main menu, I can see a lot of progress has been made compared to older builds!

![Desktop Screenshot 2020 12 04 - 18 34 46 78 (2)](https://user-images.githubusercontent.com/75380185/101195599-f11dff00-365f-11eb-8cc5-b2f8a022f92d.png)
![Desktop Screenshot 2020 12 04 - 18 34 56 05 (2)](https://user-images.githubusercontent.com/75380185/101195658-085cec80-3660-11eb-8667-24fb7aabba70.png)

![Desktop Screenshot 2020 12 04 - 18 29 21 66 (2)](https://user-images.githubusercontent.com/75380185/101194900-ec0c8000-365e-11eb-896a-190a6caeaed3.png)

**Comment by Etokapa** [comment]
Those screenshots are from Canary. You can post them on their Issue Tracker. https://github.com/xenia-canary/game-compatibility/issues

**Comment by raintrija** [comment]
544307D1-Dead or Alive 4 still has a serious problem with graphic errors in-game like the pictures attached ( graphics errors like: don't have a picture of the character on selection menu, cutscenes don't display, serious in-game display).

![loi 1](https://user-images.githubusercontent.com/89759173/131604909-bc29e83c-ce0a-4788-8e74-1dac980853f4.png)
![loi 3](https://user-images.githubusercontent.com/89759173/131605179-da370227-c391-407d-aff8-56994b8a223e.png)
![loi 4](https://user-images.githubusercontent.com/89759173/131605244-bcf8b9ac-1113-46d8-87d0-5ec8eb3e4153.png)

Make this game is unplayable in the current state of emulation, Test on master build 28-08-21 https://github.com/xenia-project/xenia/commit/6986d6c7e8511bf402394959a525449f792d9713 

[xenia.zip](https://github.com/xenia-project/game-compatibility/files/7087951/xenia.zip)

**Comment by daninthemix** [comment]
[xenia.zip](https://github.com/xenia-project/game-compatibility/files/7149227/xenia.zip)

Using the latest version of Xenia Canary (9c74b4cab) the game runs quite well, but unfortunately the emulator (NOT the guest / VM) will crash quite frequently. In my testing you are unlikely to manage 3 fights in a row without a crash. Log is attached, in case it helps.

It's more likely to crash when changing map or character, or at the end of fights.

Also, prior to it crashing, the sound will sometimes cut out for a few minutes.

**Comment by tabnk** [comment]
xenia-canary 47222be introduced black texture on character.

**Comment by tabnk** [comment]
As of today https://github.com/xenia-canary/xenia-canary/releases. The following issue still exist.  Press F5 won't fix the issue.

![image](https://user-images.githubusercontent.com/10874582/173532445-2ffa28a9-9503-46af-8f1e-e73fb88b6792.png)

**Comment by grydian** [comment]
Any chance this can get fixed?  I absolutely love this game.

**Comment by kasumi900** [comment]
Graphic Glitches but those is known , i can go until endgame fight but by the cutscene it freezes before it crashed there.

[xenia.log](https://github.com/xenia-project/game-compatibility/files/10479769/xenia.log)
![image](https://user-images.githubusercontent.com/102263685/214042912-5a9183dd-d271-4e15-916f-2fccb7f1cc0d.png)

**Comment by kaionemu** [comment]
> Graphic Glitches but those is known , background music is missed in some stages , i can go until endgame fight but by the cutscene it freezes before it crashed there.I have made a pic where it froze.
> 
> [xenia.log](https://github.com/xenia-project/game-compatibility/files/10479769/xenia.log) ![image](https://user-images.githubusercontent.com/102263685/214042912-5a9183dd-d271-4e15-916f-2fccb7f1cc0d.png)

i figured out how to fix! in ur display settings go to post processing and use extreme quality for anti aliasing :)
![Screenshot_20230225_015659](https://user-images.githubusercontent.com/126360116/221381524-ec9b80fc-fda9-42a6-8bbf-d26e0358e103.png)

**Comment by kaionemu** [comment]
> 544307D1-Dead or Alive 4 still has a serious problem with graphic errors in-game like the pictures attached ( graphics errors like: don't have a picture of the character on selection menu, cutscenes don't display, serious in-game display).
> 
> ![loi 1](https://user-images.githubusercontent.com/89759173/131604909-bc29e83c-ce0a-4788-8e74-1dac980853f4.png) ![loi 3](https://user-images.githubusercontent.com/89759173/131605179-da370227-c391-407d-aff8-56994b8a223e.png) ![loi 4](https://user-images.githubusercontent.com/89759173/131605244-bcf8b9ac-1113-46d8-87d0-5ec8eb3e4153.png)
> 
> Make this game is unplayable in the current state of emulation, Test on master build 28-08-21 [xenia-project/xenia@6986d6c](https://github.com/xenia-project/xenia/commit/6986d6c7e8511bf402394959a525449f792d9713)
> 
> [xenia.zip](https://github.com/xenia-project/game-compatibility/files/7087951/xenia.zip)

i figured out how to fix! in ur display settings go to post processing and use extreme quality for anti aliasing :)
Screenshot_20230225_015659

**Comment by tabnk** [comment]
During my short test on the latest version, it had more or less fixed with clear memory page. Yes playable now but with mirror texture issue.

**Comment by Kiritoh54** [comment]
Hello, the game works for me with good graphics and everything is visible, the only problem is that it stops, it runs very slowly, any solution?

**Comment by dracon1941** [comment]
Still crashes loading Alpha-152 for some reason, shader issue?

**Comment by DeijaVu44** [comment]
hello, the game is playable for me, but still the alpha 152 fight makes the game crash, is there any new solution for that? thank you all

**Comment by WAZAAAAA0** [comment]
Alpha-152 crash was fixed with [0ad1e3d](https://github.com/xenia-canary/xenia-canary/commit/0ad1e3d5855cdf8e3c4ee20f7d3ba5ebc20c2edd) [build](https://github.com/xenia-canary/xenia-canary/releases/tag/0ad1e3d), making Story Mode fully playable! Proof:

![DOA4 - Alpha-152 xenia](https://github.com/user-attachments/assets/c48a3ac5-0872-41d9-a295-e4063161dc15)

**Comment by StrangeguyStrangeperson** [comment]
OS: Windows 11 Professional
CPU: Intel Core i7-14700K
GPU: Nvidia RTX 4070Ti SUPER 16GB
RAM: 48GB

Game hits an unhandled exception and crashes after the Team Ninja intro video. Error code is displayed as follows:

![Xenia Unhandled Exception](https://github.com/user-attachments/assets/a51b0140-844c-4769-bc02-627ad34062e6)

I've been installing/repairing any Visual C++ libraries and hardware drivers to make sure there isn't an issue there, but so far nothing has affected the situation. As well, testing other games in my library confirms that this is the only game to hit this kind of error: Even other Team Ninja games like Dead or Alive Xtreme 2 work fine, for instance.

Log file is included for further information. For configuration, I've tried with both dedicated XMA thread enabled and disabled, with no effect in either case.

[xenia.log](https://github.com/user-attachments/files/17104701/xenia.log)
