### ISSUE TITLE
454107D9 - Need for Speed Most Wanted (2005)

### ISSUE THREAD

**Issue by TotalCaesar659** [xenia-project/game-compatibility#491]
[Marketplace](https://www.google.com/?q=Need%20for%20Speed%20Most%20Wanted%20(2005)%20Xbox%20360%20game)

Tested on (https://github.com/benvanik/xenia/commit/3d1d4dea47dd95117befe436ed292ad79ca5ee13)

# Issues:
After intro movies, the game crashes after trying to press A to continue.

# Log:
[Log file](https://drive.google.com/file/d/0B7KpdfS_wYnZLUdhMXg4bXlKTGs/view)

# Screenshot(s):
![0001](https://cloud.githubusercontent.com/assets/14265316/16474948/5bfd1f06-3e83-11e6-8e5b-29227566b4a3.jpg)
![0003](https://cloud.githubusercontent.com/assets/14265316/16474947/5bfcc218-3e83-11e6-98b3-bc8394df1101.jpg)
![0004](https://cloud.githubusercontent.com/assets/14265316/16474951/5c00e03c-3e83-11e6-8565-5481d290b026.jpg)
![0009](https://cloud.githubusercontent.com/assets/14265316/16474952/5c02b808-3e83-11e6-90b8-c24b4f1fe0b4.jpg)
![0011](https://cloud.githubusercontent.com/assets/14265316/16475027/db2d90d0-3e83-11e6-89ae-9090f49419f4.jpg)

# Labels:
(state-intro)

**Comment by Deathlock47** [comment]
I managed to bypass the crash and get ingame by setting the timescale to 4x. It also has to be turned down to 2x or less before the videos or they get stuck.
Video: https://www.youtube.com/watch?v=waha-75R6Ig
A screenshot from quick race:
![xenia 2016-09-13 20-09-16-94](https://cloud.githubusercontent.com/assets/22158671/18488925/2fcd6a78-7a04-11e6-9276-9f49a9cf03ef.jpg)

**Comment by Deathlock47** [comment]
@Razzile update the labels please

**Comment by Deathlock47** [comment]
I'm 2 weeks late but here're the logs anyway
[OpenGL](https://mega.nz/#!r1phiIJI!USs4-_S_cOVjVnK9urLPXHPlYf5D6ccac4RsGrBThnY) (warning, enormous)
[Vulkan](https://gist.github.com/Deathlock47/d442a736c2ad122d1552356fab39dd47) (crashes on startup for some reason)

**Comment by DiamondMaster07** [comment]
I don't know if it's a good thing or a bad thing, but crashing takes much longer on https://github.com/benvanik/xenia/commit/8ccefa160076c13a1cb4e2a8e1d7fc7e254a6b4b. Freezes on taking control over car, then waits, then crashes. This was the first time it happened(atleast for me)

Log:
[xenia.txt](https://github.com/xenia-project/game-compatibility/files/958987/xenia.txt)

**Comment by DiamondMaster07** [comment]
HUGE PROGRESS!
Tested on: https://github.com/benvanik/xenia/commit/1e9786eae395ef09de81e82d1c13d6426c7dc6c5
Game does not crash when taking over control a car!
HUD is not visible
The 4x timescale trick still needed
And I'll try to finish a race(didn't crashed, I quitted)
And I'll try to record a video

**Comment by DiamondMaster07** [comment]
Video about gameplay(quick race): https://youtu.be/bCEbDGHgNN0
Forgot to send the log file(and I won't do a race again today, sorry)
@Deathlock47 Try to get to the carrer mode. I couldn't(I don't know what to press)

**Comment by Deathlock47** [comment]
@DiamondMaster07 Yep, everything works now
![xenia 2017-05-15 16-05-14-81](https://cloud.githubusercontent.com/assets/22158671/26059132/46de61e6-3989-11e7-88b7-56e1a74c4306.png)

**Comment by DiamondMaster07** [comment]
@Deathlock47 How can you go to the carrer mode? I tried everything but I'm stuck, I know the menus are functional, I just don't know what to press in what order

**Comment by DiamondMaster07** [comment]
I've found out what causes the 4x timescale bug. World updates! If you set it down to 1x, you can stay ingame as long as you don't update the world(load a new chunk).
Also, I've figured out how to get into carrer mode
And another thing. If you put the devbuild xex file to the retail files, you can enable debug menu which appears as broken as any other hud elements, but atleast it loads

**Comment by osdeverr** [comment]
@DiamondMaster07 Not really. You need to modify that devbuild xex as I did, it's way bigger and it's rebuilt for retail X360.

**Comment by osdeverr** [comment]
@Deathlock47, nice to meet you, my old heli fan :P

**Comment by Deathlock47** [comment]
@osdeverr Glad to see you too fella. How did you modify the dev xex so it doesn't crash?
Btw any of you had success booting on Vulkan? I still get an instant crash to this day

**Comment by DiamondMaster07** [comment]
Vulkan still crashes for me
Osdever can't test Xenia cuz his cpu is not compatible with xenia

**Comment by DiamondMaster07** [comment]
Tested on: https://github.com/benvanik/xenia/commit/2cf0b39bf5454ffee8055ad33d92f6ff991a1c8f
Game now has an issue with textures, only car model's textures load.
![desktop 08 08 2017 - 16 18 39 07](https://user-images.githubusercontent.com/26389402/29076376-a6199248-7c55-11e7-9dac-76e233f08c2c.png)
![desktop 08 08 2017 - 16 18 25 06](https://user-images.githubusercontent.com/26389402/29076380-a6887b40-7c55-11e7-91bc-c127d15fab05.png)
![desktop 08 08 2017 - 16 17 48 05](https://user-images.githubusercontent.com/26389402/29076377-a61a1a4c-7c55-11e7-9065-dbaa9ee41960.png)
![desktop 08 08 2017 - 16 17 42 04](https://user-images.githubusercontent.com/26389402/29076375-a618c962-7c55-11e7-9947-faa76cf6ad88.png)
![desktop 08 08 2017 - 16 17 35 03](https://user-images.githubusercontent.com/26389402/29076379-a61b3f9e-7c55-11e7-9b45-7ac59cd07ecf.png)
![desktop 08 08 2017 - 16 17 27 02](https://user-images.githubusercontent.com/26389402/29076378-a61ac53c-7c55-11e7-80c7-6e117cd12b22.png)

**Comment by DiamondMaster07** [comment]
Latest issue fixed in https://github.com/benvanik/xenia/commit/f162b045ff33d92876abe5400103c63db6f1cbff

**Comment by Parovozik** [comment]
Tested on (https://github.com/benvanik/xenia/commit/09c29bbdc5167347268f6a78163f30a09032ef1a)
# Screenshots (OGL)
![desktop 08 10 2017 - 16 15 58 08 mp4_snapshot_06 07_ 2017 08 10_21 19 14](https://user-images.githubusercontent.com/19775644/29185371-aeb672a0-7e11-11e7-9cb1-41340bdfa45a.jpg)
![desktop 08 10 2017 - 16 15 58 08 mp4_snapshot_06 51_ 2017 08 10_21 19 25](https://user-images.githubusercontent.com/19775644/29185374-b100e040-7e11-11e7-83ac-fc3378ae30dd.jpg)

**Comment by osdeverr** [comment]
try to complete the prologue

**Comment by osdeverr** [comment]
btw as i can see normal maps are borken @Parovozik

**Comment by DiamondMaster07** [comment]
Tested on: https://ci.appveyor.com/project/benvanik/xenia/build/1.0.957-master
Vulkan works, same issues as OpenGL, but HUD renders correctly, half of the screen is no longer covered and runs on a better FPS.
Here's a video using the devkit version of the game(no gameplay/graphical differences, only a developer menu) https://youtu.be/ybkcVgWyrvU

However, Vulkan crashes on https://ci.appveyor.com/project/benvanik/xenia/build/1.0.958-master

**Comment by Razzile** [comment]
@DiamondMaster07 that doesn't make any sense as between 957 and 958 the only change was to the doc files

**Comment by osdeverr** [comment]
L I T

btw it was me who made the devbuild work *shameless self-promotion*

**Comment by DiamondMaster07** [comment]
Thanks to @Parovozik (https://github.com/benvanik/xenia/issues/799) I managed to stay ingame with 1x timescale by removing every sound file from the game.
Video: https://youtu.be/hU_UwIi3HA8

@Razzile I tested it multiple times, https://ci.appveyor.com/project/benvanik/xenia/build/1.0.958-master broke something and Vulkan crashes on this build while https://ci.appveyor.com/project/benvanik/xenia/build/1.0.957-master works just fine

**Comment by Parovozik** [comment]
@DiamondMaster07 What software you used for remove game files? I see there specific archives :)

**Comment by DiamondMaster07** [comment]
@Parovozik That's the developer build of the game(about 1 month before the actual release). According to xenia's rules, I'm not allowed to share the download link here, but we have a tutorial how to get it and play it in xenia in our Discord server: https://discord.gg/zmKaf5R

**Comment by Parovozik** [comment]
@DiamondMaster07  Ok. Thanks! :)

**Comment by DiamondMaster07** [comment]
Ran some tests(most of the shaders(VisualLookFilter) and UI are removed inside the devkit version of the game to save your eyes and make easier to spot the differences)

Tested with: https://ci.appveyor.com/project/shadowbrony33/xenia-jime1
(this is 1.0.957 with OGL4.6 support)

OpenGL: working shadows and normal maps, somewhat working reflections, but poor performance, broken car shadow textures and broken UI everywhere
![desktop screenshot 2017 12 04 - 18 32 43 16](https://user-images.githubusercontent.com/26389402/33574474-7a5e9540-d939-11e7-9e83-d9086842ed10.png)

Vulkan: broken shadows and reflections, broken normal maps in most cases, working UI and playable performance
![desktop screenshot 2017 12 04 - 18 35 44 96](https://user-images.githubusercontent.com/26389402/33574639-11ddf910-d93a-11e7-92f1-a17cad360eb7.png)

Issues with both version:
[This](https://github.com/benvanik/xenia/issues/799)

VisualLookFilter is broken(too much)
OGL
![desktop screenshot 2017 12 04 - 18 46 23 83](https://user-images.githubusercontent.com/26389402/33574773-99858db0-d93a-11e7-8d44-d883e89a66ee.png)

Vulkan
![desktop screenshot 2017 12 04 - 18 48 25 45](https://user-images.githubusercontent.com/26389402/33574792-a6f439c4-d93a-11e7-86a3-662148cc36be.png)

**Comment by Deathlock47** [comment]
Goes ingame on Vulkan again
Now shadows work properly, however the lower part of the screen frequently turns white
![144](https://user-images.githubusercontent.com/22158671/34321584-798a84a0-e823-11e7-8a5a-d1aec9291fa3.png)
![153](https://user-images.githubusercontent.com/22158671/34321580-730ebc5e-e823-11e7-9b27-b0b2784614d5.png)

**Comment by DiamondMaster07** [comment]
![desktop screenshot 2017 12 23 - 21 58 15 48](https://user-images.githubusercontent.com/26389402/34322775-07d26c52-e831-11e7-8079-08150f69db9b.png)
![desktop screenshot 2017 12 23 - 21 58 06 52](https://user-images.githubusercontent.com/26389402/34322776-07f47cd4-e831-11e7-8f3b-6dc66358ffd7.png)
Here're some screenshots with VisualLookFilter turned off

**Comment by DiamondMaster07** [comment]
In short: Vulkan now has all the visual bugs except for the HUD that OGL has and has worse framerate than on 1.0.957

**Comment by DiamondMaster07** [comment]
Some findings: when a NIS plays. the lightning is correct
Prologue NIS
![desktop screenshot 2018 01 27 - 17 45 50 50](https://user-images.githubusercontent.com/26389402/35482628-53bb710e-0438-11e8-95e3-1d902aac80a8.png)
![desktop screenshot 2018 01 27 - 17 46 22 70](https://user-images.githubusercontent.com/26389402/35482633-755033cc-0438-11e8-914c-654af7e2c84b.png)
Race intro NIS
![desktop screenshot 2018 01 27 - 19 13 13 53](https://user-images.githubusercontent.com/26389402/35482660-c523f870-0438-11e8-9aba-f845f13268ac.png)

Here's a video showing correct lightning when a NIS plays, then showing broken lightning, when going ingame: https://youtu.be/2j_kbcZ6k-s

Also, when a frame breaks, shaders still apply(also seen in the video)
![desktop screenshot 2018 01 27 - 17 45 56 48](https://user-images.githubusercontent.com/26389402/35482676-fd20ee4a-0438-11e8-9063-b6dcaa4dafdf.png)
This is the reason why half of the picture goes white sometimes(broken shaders)
![desktop screenshot 2018 01 28 - 14 45 09 84](https://user-images.githubusercontent.com/26389402/35482749-e3593520-0439-11e8-9fa4-5ac11ae96bbe.png)

**Comment by DiamondMaster07** [comment]
Tested on https://github.com/benvanik/xenia/commit/e4bc5968870f55cbebedb0aba5a5cb30a1962fa3
Previously bugged half-frames now cover the entire screen and are black, resulting in covering the whole 3D part of the garage menus and black flashes ingame

**Comment by Deathlock47** [comment]
@DiamondMaster07 As far as I've investigated, the HDR shader still doesn't work correctly during the NIS, it just gets minimized when the depth of field effect is present. The DOF itself doesn't apply even though it used to in OpenGL, here's an old screenshot with it working correctly

![xenia 2016-09-27 03-17-13-79](https://user-images.githubusercontent.com/22158671/36395660-4a1a161a-15cb-11e8-9de6-eedf31bbde0d.png)

**Comment by Deathlock47** [comment]
Since xenia-project/xenia@425764698 some textures are garbled and it's hard to go ingame now, loses graphics device very frequently

![318](https://user-images.githubusercontent.com/22158671/40720761-7bf1e66a-6420-11e8-80a7-9c86df0d8a4c.png)

**Comment by Parovozik** [comment]
Tested on Xenia-DX12 (https://github.com/xenia-project/xenia/commit/d827bbeb6cc5bd2120350e9dc0c4998a8c36a1fe)
Log: 
[NFS MW DX12.log](https://github.com/xenia-project/game-compatibility/files/2448601/NFS.MW.DX12.log)
Goes ingame but some lighting troubles:
![bandicam 2018-10-05 03-37-34-385](https://user-images.githubusercontent.com/19775644/46510724-652ba500-c853-11e8-80e9-eed925557464.jpg)
![bandicam 2018-10-05 03-38-26-106](https://user-images.githubusercontent.com/19775644/46510712-5c3ad380-c853-11e8-9365-1ccc0059c5da.jpg)
![bandicam 2018-10-05 03-38-51-618](https://user-images.githubusercontent.com/19775644/46510714-5f35c400-c853-11e8-87db-5fd96d78da29.jpg)

**Comment by ThatD07** [comment]
But better graphics than Vulkan: half of the screen isn't covered with a black/white rectangle, car reflections and rearview mirror work properly

**Comment by ThatD07** [comment]
Tested on https://github.com/xenia-project/xenia/commit/90c9c24ca5a5664789729df26071c2498df80f59 with **--d3d12_readback_resolve=true**

Graphics are emulated perfectly but performance is low
Still has CPU timing issues, free roam and races require to be launched at 0.13X CPU timescale
![xenia-2](https://user-images.githubusercontent.com/26389402/62473843-7efe8700-b799-11e9-9e19-6cd69f29bd5e.png)
![unknown](https://user-images.githubusercontent.com/26389402/62473855-8887ef00-b799-11e9-80de-3015a051d001.png)
![unknown](https://user-images.githubusercontent.com/26389402/62473856-8887ef00-b799-11e9-93cf-206f48849e2d.png)

**Comment by HarGabt** [comment]
Tested on https://github.com/xenia-project/xenia/commit/5558c8aafefffca68ada82d3d7a389ac8fcedde6
Graphics without using **d3d12_readback_resolve=true** got a little better, though there are issues with overbright objects (particles, sky, etc)

Also found out that using **disassemble_functions=true** lets several chunks of audio load after pressing start without using time scale. Although after a new chunk of sfx loaded and played, audio mutes and still won't let go into gameplay. So, time scale x4.00 is still required to get into gameplay.

[log file](https://github.com/xenia-project/game-compatibility/files/4294841/xenia.zip)

![Снимок экрана (41)](https://user-images.githubusercontent.com/44652400/76014048-65d9d680-5f32-11ea-843c-98a06e15d4df.png)
![Снимок экрана (42)](https://user-images.githubusercontent.com/44652400/76014918-e1885300-5f33-11ea-8ce3-0840da5e102d.png)
![Снимок экрана (49)](https://user-images.githubusercontent.com/44652400/76015006-01b81200-5f34-11ea-8bd3-f02098595dbe.png)
![Снимок экрана (47)](https://user-images.githubusercontent.com/44652400/76014975-f369f600-5f33-11ea-83ff-4f380a407b0d.png)

**Comment by Triang3l** [comment]
GPU>CPU readback needed for correct eye adaptation to brightness.

**Comment by Back2Life888** [comment]
The shaders are fixed by custom patches but that belongs in Canary (unfortunately)

**Comment by ThatD07** [comment]
The "fix" doesn't fix the shaders, it just disables the HDR shader. You get the same results if you decompile the game's files and replace the HDR.fx file with another one.

**Comment by Back2Life888** [comment]
> The "fix" doesn't fix the shaders, it just disables the HDR shader. You get the same results if you decompile the game's files and replace the HDR.fx file with another one.

yeah.. About that.. I got the debug build (don't ask how) and deleted the HDR.fx.. Nothing happened.. Still the same thing bro.

**Comment by HarGabt** [comment]
Tested on https://github.com/xenia-project/xenia/commit/00e7de9297f9353aafd08ecfa99d4c5efb340c47

Lots of commits passed since my previous post, where i mentioned `disassemble_functions_true` which allowed to pass some of sfx chunks before audio crash. Now this option is not necessary to get into the game, as improvements into emulator code have been made throughout the time to make frontend (menu) sfx play fine enough without APU going silent.
Although, there may be some issues with in-game profiles: if you happen to have 2 or 3 profiles (saves), the game at start may replace one of game profiles, but it doesn't happen when you check profiles in alias manager.

But overall, the graphics are still the same and APU still goes silent when engine sounds are played.

[log file](https://github.com/xenia-project/game-compatibility/files/8086865/xenia.zip)

**Comment by PokeyManatee4** [comment]
Hang on that don't look like nfs mw

**Comment by MaksimKuznetzov** [comment]
Hey Guys. I have such a problem, after the end of the race, my game just freezes on this race that I participated in, I tried to pass the prologue, but every time such a problem. Please tell me how to solve this problem?

**Comment by HarGabt** [comment]
@MaksimKuznetzov Use [Canary build](https://github.com/xenia-canary/xenia-canary)  with [patches](https://github.com/xenia-canary/game-patches). APU issues with Most Wanted and Carbon haven't been solved yet. 

<details> 
  <summary>Translation to Russian, considering he speaks russian</summary>
   A1: JavaScript 
</details>

**Comment by HarGabt** [comment]
@MaksimKuznetzov  Use [Canary build](https://github.com/xenia-canary/xenia-canary)  with [patches](https://github.com/xenia-canary/game-patches). APU issues with Most Wanted and Carbon haven't been solved yet. 

<details> 
  <summary>Translation to Russian, considering he speaks russian</summary>
   @MaksimKuznetzov Качай [Canary версию эмулятора](https://github.com/xenia-canary/xenia-canary) вместе с [патчами](https://github.com/xenia-canary/game-patches). Проблемы со звуком в МВ и Carbon ещё не решили.
 
</details>

**Comment by MaksimKuznetzov** [comment]
@HarGabt I already have a PC version of canary and a patch for games. I wanted to say not about the friezes, because of which the game or sound is buggy, but about the frozen picture when exiting the race.

**Comment by MaksimKuznetzov** [comment]
I already have a PC version of canary and a patch for games. I wanted to say not about the friezes, because of which the game or sound is buggy, but about the frozen picture when exiting the race.

**Comment by TorutheRedFox** [comment]
https://github.com/xenia-project/xenia/pull/2199 fixes most of the APU issues making the game actually somewhat playable

**Comment by samcomeau** [comment]
The game still freezes in Canary at the end of the race. Audio issues remain. Extreme bloom with patch off (video shown with patch). 

https://www.youtube.com/watch?v=Z6YnRPAqV4U&ab_channel=SamuelComeau

**Comment by Zaccoder56** [comment]
Nfsmw audio cuts off sometimes when playing the game and so does jumping to the safe house freezes the game on Xenia canary Xma decoder

**Comment by Faze15** [comment]
For those who have issue at the end of the race - switch from d3d12 to vulkan.
After that no freezes at the end of the race, you may buy car and continue the race. 
Also recomend to swtich back to d3d12, because perfomance at vulkan ain't that good. 
Plus changed use_dedicated_xma_thread = false, use_new_decoder = true and apu = "sdl" to fix "silent" audio.
![11](https://github.com/user-attachments/assets/ff895f33-7177-4695-b321-3c2d6ca5f1fe)
![33](https://github.com/user-attachments/assets/48bf9c59-6f9e-4e61-931a-625540b06ad6)

**Comment by Keith4356** [comment]
Someone know how to fix sound after buying new car? (I use new xma decoder, USA and EUR works same, audio patch works bad)

**Comment by Szw4gier** [comment]
With new xma decoder and setting **use_dedicated_xma_thread = false** Audio seems to be alright and game runs fine, UNLESS you play a race with a Cobalt SS. Either you run quick race with it, opponent drives one or you pick one after prologue. After about 5-10 seconds audio cuts off and nearest return to safehouse/main menu causes freeze.

**Comment by Faze15** [comment]
> With new xma decoder and setting **use_dedicated_xma_thread = false** Audio seems to be alright and game runs fine, UNLESS you play a race with a Cobalt SS. Either you run quick race with it, opponent drives one or you pick one after prologue. After about 5-10 seconds audio cuts off and nearest return to safehouse/main menu causes freeze.

In patches, you have "Skip audio loop stuck code", the only issue is that the audio at some moment might be silent.
Basically, you can finish a full game, but with "sometimes" silent audio. 
Personally, I'm currently at the 8th member of the blacklist, there are no  freezes at all, only audio issues.
Plus, if you have silent audio, just reset the game and launch again, the only problem is that when beating a blacklist member, the audio might be silent, and you can't restart the game without losing progress.

**Comment by Szw4gier** [comment]
> > With new xma decoder and setting **use_dedicated_xma_thread = false** Audio seems to be alright and game runs fine, UNLESS you play a race with a Cobalt SS. Either you run quick race with it, opponent drives one or you pick one after prologue. After about 5-10 seconds audio cuts off and nearest return to safehouse/main menu causes freeze.
> 
> In patches, you have "Skip audio loop stuck code", the only issue is that the audio at some moment might be silent. Basically, you can finish a full game, but with "sometimes" silent audio. Personally, I'm currently at the 8th member of the blacklist, there are no freezes at all, only audio issues. Plus, if you have silent audio, just reset the game and launch again, the only problem is that when beating a blacklist member, the audio might be silent, and you can't restart the game without losing progress.

Yes, I know about that but thank you for mentioning this anyway. What I'm talking about is that with patch off and new xma decoder plus disabled dedicated thread, there is no buggy audio and game runs well. You can finish prologue, play quick races and do challenge series, unless you get cobalt ss in game.

I'm writing this so maybe someone could write a new patch that could make game audio less buggy, maybe something to disable particular cobalt ss sound that breaks the audio and freezes game.

**Comment by Margen67** [comment]
Xenia Canary issue: https://github.com/xenia-canary/game-compatibility/issues/28

**Comment by CooleyZ801** [comment]
Using all Patches, Running Vulkan (same issue on D3), Setting timescale to 4x and still getting a crash when finishing prologue race.
