### ISSUE TITLE
4D53085B - Halo: Reach

### ISSUE THREAD

**Issue by raven02** [xenia-project/game-compatibility#52]
Marketplace - http://marketplace.xbox.com/en-US/Product/Halo-Reach/66acd000-77fe-1000-9115-d8024d53085b

Tested against https://github.com/benvanik/xenia/commit/fc7695f874f9df1636c06aa0984c7f67a2810a36

Bootup okay but stop after intro and cannot reach title screen

It is state-load

**Comment by raven02** [comment]
This is full video from youtube  https://www.youtube.com/watch?v=-BwEVsGAZU0

**Comment by DrChat** [comment]
Probably similar to what's happening with Halo 3. The main thread dies early unable to read game data but the intro plays on another thread.

**Comment by DrChat** [comment]
Okay, so an update on Halo games: Looks like they use encryption/whatever to verify if .map files are valid (and signed). Need to implement kernel encryption functions.

**Comment by Razzile** [comment]
I hope one day xenia will accept patches so I can patch those checks out and have some fun like they are having with Halo Online :P

**Comment by theoldsport** [comment]
Looks like we're in the menu, fellas! Here's the update as of 11/9/2015 - https://www.youtube.com/watch?v=Lns0NAV1MAA

**Comment by VeteranREAL** [comment]
Tried starting the campaign yet? How did you get onto the menus? :D

**Comment by theoldsport** [comment]
Spamming B during the intro allows the menu to load. It may not work with the latest build though. 
As far as starting the campaign goes, I think I tried to load something after selecting the difficulty. It seems to spit out an error but I can't read it due to the corrupted visuals.

**Comment by no1dead** [comment]
@theoldsport by any chance the error have 2 more options on it if you move up and down. I also believe its because its not logged in?

**Comment by theoldsport** [comment]
@no1dead I'll check when I can. I'm wondering if that's the issue as well. If I still had my 360, I could test the actual behavior. I suspect it's either the lack of signing in or not installing the game (or just something else). Both require unimplemented functions I believe. Have the required "kernel encryption functions" described by @DrChat been implemented? 

I'll upload a log when I test it again. If I remember correctly, Xenia was definitely trying to sign in to xbox constantly. Maybe this is why spamming B is necessary to get into the menu in the first place, since it cancels the sign-in prompt.

**Comment by theoldsport** [comment]
Alright I tried to load the campaign again and couldn't select any options on the error prompt. I could only press A and in response to the error. 

<a href="https://drive.google.com/file/d/0Bw1m9gdt8DfpZF9RYWtLNEV6YTA/view?usp=sharing">Here's a log</a>

**Comment by no1dead** [comment]
I'm actually pretty sure it's because there is 4 people, reach is max for 2.

**Comment by no1dead** [comment]
It is because the campaign can only be run by 2 people, so I guess if you can remove 2 or all 3 and have one person there.

**Comment by theoldsport** [comment]
There is only one controller connected though. Wouldn't the game just ignore extra controllers anyway?

**Comment by no1dead** [comment]
No Xenia forces players as a debug thing. I guess.

**Comment by theoldsport** [comment]
Ah, so would the error occur on a real 360 with four players connected?

**Comment by no1dead** [comment]
Yup game has a max for people for campgin and firefight.

**Comment by theoldsport** [comment]
Well, there's this- https://www.youtube.com/watch?v=bzOPJO9-HXY

**Comment by no1dead** [comment]
Yeah well don't think we can do that yet :P

**Comment by theoldsport** [comment]
So I'm gonna have to compile Xenia without the forced extra players, eh? I don't even know what code to omit :|

**Comment by no1dead** [comment]
Yeah never do I.

**Comment by DrChat** [comment]
Xenia only reports that one player is logged in at the moment. Issue is probably still related to crypto, but we won't know until we can see what the dialog says.

**Comment by VeteranREAL** [comment]
This needs state Menus

**Comment by VeteranREAL** [comment]
Thanks :D

**Comment by lordnihrain** [comment]
What kind of crypto is required?

**Comment by Scottyyyy** [comment]
I know that theoldsport was able to see the main menu before, but in the newest build I can now see the menu but it crashes once there. GTX 750ti i5 4590 Tested with https://github.com/benvanik/xenia/commit/0e1c91681d5edfffd41f0a3badba258464e8784e build. ![halo reach menu crash](https://cloud.githubusercontent.com/assets/20063269/16223829/6e274ad6-37de-11e6-9eb0-a7c2202a3565.PNG)

**Comment by HaydnTrigg** [comment]
I have been doing some research into why these menus are so messed up. Halo Reach is rendering all of the UI for a particular block (blocks being, main menu, player menu, navigation, options etc.) into a renderbuffer and then compositing that down into the final menu.

The problem is that these buffers are never being cleared, is this perhaps some missing functionality like IDirect3DDevice9::Clear not being implemented yet? I haven't found much reference to clearing of buffers except for under 'IssueCopy' for what I assume is the flushing of the EDRAM buffer?

So I have mangled up some code that at least clears the buffer, the issue is that these buffers are also cleared I think when they are bound so anything that was rendered to them is lost, all of the render buffers are just blank textures.

The result looks like this:
![Image of Halo Reach with Clear Buffers](http://i.imgur.com/VqfCgUB.png)
[More images here](http://imgur.com/a/y609P)

I have also noticed that this functionality might be the cause of problems in various other games. I've been messing around with Worms 2 Armageddon lately and the very start of the game on the Xbox Live menu suggests that this clearing function is not working either.

Some other things. Halo 3 and Halo Reach make an extremely heavy use of 1D textures, these textures are used as gradients for everything under the sun. I've noticed that the functionality to add 1D textures in the OpenGL4 project is currently not implemented along with 3D textures.

**Comment by DrChat** [comment]
@HaydnTrigg Thank you for the write-up, that's actually really useful!

Are menu clears screwed under Vulkan as well? I've noticed that clears aren't quite working under some circumstances.

**Comment by spectrumm** [comment]
Menu music loads, except menu is broken on newest build.

**Comment by spectrumm** [comment]
[New Log](https://gist.github.com/spectrumm/f482fd73b65d0db991bc94b522176f66)

**Comment by HaydnTrigg** [comment]
@DrChat Totally missed your message, I'll have a rip through tonight and test out the latest versions of Xenia and provide some feedback

I did some testing looking at which commands are being handled in different switch statements, I believe this clearing is just held up with a specific type of clear command that hasn't been accounted for yet

When I also did my testing, I was using the OpenGL. There wasn't support for 1D or 3D textures I believe because I ran into some issues there. Halo makes use of heaps and heaps of 1D textures that are used against gradient textures 0-1 in the gradient is the X co-ordinate of the 1D texture. (This is also heavily used throughout Halo 3 for all of the weapon effects)

![Gradient Texture Example from Halo 3](http://i.imgur.com/2kaEpEv.jpg)

Something I noticed from a build a little while back, not entirely sure which version specifically. But the main menu background texture was loading and I believe the shader was also working for it as well. I was unable to proceed as accepting the dialogue at the main menu causes a freeze, same issue as spectrumm I believe.

**Comment by DrChat** [comment]
@HaydnTrigg As far as I know there should only be two possible clear commands.
One is through a drawcall where they render a rectangle into the framebuffer, the other is a clear after copy indicated by some GPU registers.

I'll have to look into implementing 1D textures. I think we're on the verge of them being supported in Vulkan.

Thanks for the info though - it is *incredibly* useful!

**Comment by HaydnTrigg** [comment]
I haven't had the time yet to go through yet, but I had a quick check today looking through recent changes. We may have fixed the clearing bug 👍 

These images are from a special build of Halo Reach. This first image is loading the video.
![image](https://cloud.githubusercontent.com/assets/12438599/25581806/14809ef0-2ec9-11e7-9345-e2366c7c69f3.png)
Here is the initial screen presented to the user. These black regions used to work and the outsides flicker with white. I believe this could be a simple blending issue. I believe these are transparent, and have a premultiplied alpha? So I am wondering if they're being rendererd as opaque and the alpha value is zero. (Completely just a hunch)
![image](https://cloud.githubusercontent.com/assets/12438599/25581820/2a1238a0-2ec9-11e7-8f6c-b43027c1499e.png)
Here is a picture that took me forever to take. This is what I am talking about with the flicker.
![image](https://cloud.githubusercontent.com/assets/12438599/25581967/f81b76e4-2ec9-11e7-9933-18fca3281085.png)

I am able to proceed through into the menu. This version of my game has been extensively modified just for note, however I do not expect this to affect the results that I am presenting as they're unrelated to graphics rendering and are there to unlock all of the features.

This main menu sequence does not have any flickering around the black regions. The background is heavily broken, I believe this is a shader issue because the game used to render out noise and there might be a precision issue?
![image](https://cloud.githubusercontent.com/assets/12438599/25582006/21bbc396-2eca-11e7-8a8f-54cde3d1afb0.png)

If I immediately press A again. I am able to enter what I believe is the forge lobby. The player name User is present, but isn't rendering correctly with some yellow background? Could this perhaps be the same blending issue? Players who are the party leader have yellow text iirc.
Staying on this screen for an extended period of time leads to a crash. I can provide logs if you require.
![image](https://cloud.githubusercontent.com/assets/12438599/25582052/57bad856-2eca-11e7-97ca-88736fadf310.png)

If I try to rush through the game, pressing A as quickly as I can to get to this same screen. I am presented with a slightly different screen, and the waiting for a crash appears to happen sooner.
![image](https://cloud.githubusercontent.com/assets/12438599/25582123/a88eb324-2eca-11e7-8c90-97a71da534a6.png)

(I am going to do some more research, but I am having Vulkan cause me BSOD regularly)

Good work so far, it would be very useful for me to know the important features that have been changed around the issue highlighted since my initial investigation into the buffers clearing.

I have a hunch we are now dealing either incorrect buffer formats, blending issues or insanity. But the clearing has made improvements. 👍

**Comment by HaydnTrigg** [comment]
Some more research that I have found while debugging.

The game is asking for FetchOpcode::kGetTextureGradients @ SpirvShaderTranslator::ProcessTextureFetchInstruction I am able to get the game running at this point by applying this value to the top of the switch statement.

![image](https://cloud.githubusercontent.com/assets/12438599/25583130/9dab7d20-2ecf-11e7-9652-c1d819f7b1f5.png)

VulkanCommandProcessor::PopulateVertexBuffers has a lot of fetch type 3's called in it. Currently there is an assert in this function. Could someone illuminate the purpose of this function and what the fetch type 3 means? I think it might be worth replacing this value with an enumeration.

When proceeding through the menus and immediately at the main menu in retail, an error is caused on vkQueueWaitIdle in trampoline.c

**Comment by spectrumm** [comment]
Build 1.0.937 gets in menu.
![screenshot_43](https://user-images.githubusercontent.com/23747820/29534408-3a9d7af0-86b6-11e7-880f-686a5e8fe2c3.png)

**Comment by DrChat** [comment]
@HaydnTrigg Fetch type 3 is a vertex fetch. Type 2 is a texture fetch.

The GetTextureGradients opcode is currently unimplemented because I'm not really sure what it does.

A crash in vkQueueWaitIdle means some graphics commands failed to execute and NVIDIA so graciously terminates Xenia for us :)

**Comment by tydowntyty** [comment]
> The GetTextureGradients opcode is currently unimplemented because I'm not really sure what it does.

A quick search of "GetTextureGradients" brings up [this](https://en.wikipedia.org/wiki/Texture_gradient).

> Texture gradient is the distortion in size which closer objects have compared to objects farther away. It also involves groups of objects appearing denser as they move farther away. Also could be explained by noticing a certain amount of detail depending on how close something is, giving a sense of depth perception. There are three main forms of texture gradient: density, perspective, and distortion of texture elements.

Hopefully this could help in some form. Unless you meant something else by "I'm not really sure what it does." In which case it could also mean something like (Beware of my guess) [this](http://lab.desilence.net/cinemascreen_test/gradient_red.png) being applied to a texture. 

![gradient_red.png](http://lab.desilence.net/cinemascreen_test/gradient_red.png)

Lets also say the red was a dirt texture and the white was a grass texture. In other words it could be a texture transition. 

***

I don't know much about this stuff. Sorry if I misunderstood anything.

**Comment by HaydnTrigg** [comment]
@Caboosium Texture gradients in Halo Reach are 1D textures that are used to take in a value and convert it to a colour. Heat is a great example so it starts off completely invisible but towards the end of the texture it becomes hotter, your gradient above would achieve that.

@DrChat As for that specific instruction, I doubt the information provided above is on the right track. But there is these `tex<dimension>Grad` functions in DirectX, it's a little vague because I don't have the code sample from before running anymore but I'll give it a whirl again soon. But is it possible that the shader is expecting to retrieve the texture but in a form with pre-computed gradients so it can do a regular texture lookup to retrieve the values or something? It's just strange in my mind for it to be asking for a texture, but also asking about gradients at the same time so this is just a completely uneducated guess at 1 am.

Does this have anything to do with it?
tex1DGrad (more specifically for Halo Reach): https://msdn.microsoft.com/en-us/library/windows/desktop/bb509679%28v=vs.85%29.aspx?f=255&MSPPError=-2147217396

**Comment by DrChat** [comment]
@HaydnTrigg I think you may be on the right track. Here's a disassembled gradients instruction:
```
// /*  129   */          getGradients r7.xy__, r4.ww, tf0
```

The instruction is taking 4 arguments, which matches the signature as described on the page you linked. My guess is argument 1 are the s,t coordinates, and argument 2 is the ddx,ddy parameter.

**Comment by HaydnTrigg** [comment]
@DrChat Using this version I was able to run my special build of Halo Reach without any issues regarding crashes, I think it's not just a case of finding a few more missing instructions. I no longer see any texture corruption on the game menu. Not really sure what the gradients are used for though because we probably can't see it yet.

![image](https://user-images.githubusercontent.com/12438599/31106078-3e92a248-a830-11e7-822c-32a7a3df858d.png)

The main menu appears to be broken still but everything is noticeably faster and more stable. Here is a picture of pressing start on the main menu, it appears that layering and blending are going okay. Could this be a problem of trying to render to anything but the main renderbuffer not working?

![image](https://user-images.githubusercontent.com/12438599/31106186-3f65bff6-a831-11e7-9753-49b43954eff8.png)

The older Halo 3 UI in my build of Reach also now works with background blurring, pretty sure that wasn't working last time
![image](https://user-images.githubusercontent.com/12438599/31106237-ac82b8fa-a831-11e7-9479-399d920078af.png)

![image](https://user-images.githubusercontent.com/12438599/31106234-a4c51be4-a831-11e7-9c21-45f944c5528d.png)

As for the Halo Reach Demo, the ESRB rating now shows at the beginning of the game. I've never seen that before. Everything else is just black at my end for the Halo Reach and Reach Demo.

Also not entirely sure by the code but it looks to me like the gradients aren't taking the texture dimension into account. There are also 1D and 3D versions of this function.

**Comment by HaydnTrigg** [comment]
@DrChat As for the Halo Reach public Beta. I am greeted with this screen on launching the game which is a big improvement since I last tried this. It appears there is something missing in regards to rendering text at the moment, I feel confident its related to incomplete 1D texture support.

![image](https://user-images.githubusercontent.com/12438599/31106905-5ab9f1be-a836-11e7-86e5-598cd9368218.png)

**Comment by Caboosium** [comment]
@HaydnTrigg
What about the full version of Halo: Reach?

Also I'm happy to see I pulled the trigger on progress! :D

Good job with the coding, btw!

**Comment by HaydnTrigg** [comment]
@Caboosium In my first post I said that Halo Reach and the Halo Reach demos are just black, hence no photos

**Comment by Caboosium** [comment]
@HaydnTrigg I had Halo Reach menus working on a release from around last Sunday or Saturday.

**Comment by Caboosium** [comment]
@HaydnTrigg the first menu after the intro is black. You might want to wait until Carter appears, then try doing...

A, B, B, B, Down, A, A, and then you should be on the campaign menu.

**Comment by Irixion** [comment]
As far as I can tell, getting in game is impossible. The game does a file integrity check and doesn’t load if it fails. On console it doesn’t this in multiplayer maps for modded files or damaged discs. I’ve seen it also on campaign. Judging from the “denied” sound effect when yourself in that menu, I’m going to assume that it is the case here.

**Comment by Razzile** [comment]
I think that's because some crypto functions aren't yet implemented in xenia so the integrity check will fail

**Comment by Caboosium** [comment]
1. Then the question is what these missing crypto functions?

2. Are we able to just able to get the game to skip the checks?

3. Can we make the check not actually check any thing but just return a good to go signal?

4. Can we make the game load a mission instead of the main menu on start-up?

5. If the missions are encrypted can we just decrypt it and do number 4? (I have seen a few exported bipes, models, etc from the game out on the web, I'm sure someone has the password(If there even is one.). )

**Comment by HaydnTrigg** [comment]
1.) These crypto functions shouldn't be an issue as the ones that would normally prevent you loading up a game are simply there to ensure file integrity presumably while loading from a disc for essential information. I believe that all of these integrity checks have been compiled directly into the executable, and they're relatively simple algorithms. The fact that we're loading up the main menu means that this is not an issue as the main menu itself is actually the same data format as the rest of the game so if we're reading the main menu reading campaign shouldn't be any different.

But just in case, my special build has all of these integrity checks removed and it works the same and does not allow me entry into any gameplay due to other issues.

2.) Already done, not an issue as I've stated above.

3.) Yes no difference.

4.) Great idea. Instant crash tho will investigate. Not really sure why this wasn't thought of before.

5.) Not necessary.

PS. The game is now allowing you guys in because according to the main menu 4 players are logged in with 3 of them having disconnected controllers from what I can make out. Because of this, the game will not let you start until you have connected these controllers and signed in, except I believe that players 2-4 are bugged in Xenia? The game is experiencing some extremely glitchy stuff in this regard and I think its got to do with the inability to assign temporary profile information such as credits, armor, colors, service tags etc.

It will be easier to diagnose once we have text working in the game and the error message will be more clear. Until then, as far as debugging goes I believe everything hinges on getting the text rendering working as well as the rest of the UI for the main menu.

**Comment by Caboosium** [comment]
Have you tried connecting 4 controllers?

**Comment by Caboosium** [comment]
> I believe that players 2-4 are bugged in Xenia? The game is experiencing some extremely glitchy stuff

I wonder if Xenia is giving all controllers the same profile. More than 1 controller with the same profile was never supported on the 360. Since we are in a emulator I would imagine that things that might seam unlikely become much more common. I wonder what other seemingly unrelated issues it could/is causing.

One other thought is can we just build for one profile and one controller? 

What about a no profile build? Then we just have to use reach temp accounts.

**Comment by no1dead** [comment]
Yeah I would say building a no profile or one profile build of Xenia would
be an ideal step to seeing how it functions.

I'd say one profile over no since if I remember correctly it'll still ask
for a save location regardless of the temp or not. But trying both never
hurts.

**Comment by Caboosium** [comment]
If I remember correctly a temp account made by reach does not do anything remotely close to game saving much less even armor customization.

**Comment by Irixion** [comment]
Halo games have file integrity checks as well as piracy checks, especially Reach. Any of these could go awry within Xenia.

**Comment by WRTuL** [comment]
That's disappointing. :c Hopefully one day we can get it to run nicely :D I'd love to help but I'm not exactly sure how to. :/

**Comment by Razzile** [comment]
those checks aren't a problem as the file integrity is fine, and as someone pointed out to me the main menu has these checks but xenia can reach the menu fine

**Comment by WRTuL** [comment]
Do you think it might be because Xenia is missing certain functions to properly run the game?

**Comment by gibbed** [comment]
The actual PPC emulation at this point is pretty solid, it's the rendering part that's likely the blocker at this point.

**Comment by no1dead** [comment]
That's probably a part of it and that Bungie liked to put pretty complex
functions that only they used so it'll need to be fixed at least for this
game alone if it were to start.

A lot of proprietary tech. But adding missing functions to Xenia can only
add to how much would have to be done specifically for reach to work.

**Comment by WRTuL** [comment]
Ahh, fair enough. Thanks for clarifying. Hopefully, we can get it to work at some point :D

**Comment by Caboosium** [comment]
Anyone make a one player build of xenia yet?

**Comment by Caboosium** [comment]
Think I managed to buy something in the shop. Instant freeze but audio kept going.

**Comment by Caboosium** [comment]
![xenia detached_80b0b66e_dec 22 2017 _ 4d53085b halo_ reach _vulkan_ 12_22_2017 2_00_01 pm](https://user-images.githubusercontent.com/14243076/34313513-8c5c1b06-e720-11e7-8bd2-ae2d873c7b36.png)
I swear I did this by accident! Normal Release version of reach!

**Comment by Caboosium** [comment]
![xenia detached_80b0b66e_dec 22 2017 _ 4d53085b halo_ reach _vulkan_ 12_22_2017 2_02_40 pm](https://user-images.githubusercontent.com/14243076/34313555-d7d94590-e720-11e7-9e63-719bc913c757.png)

Still release version of Reach.

**Comment by Caboosium** [comment]
![xenia detached_80b0b66e_dec 22 2017 _ 4d53085b halo_ reach _vulkan_ 12_22_2017 2_00_01 pm 2](https://user-images.githubusercontent.com/14243076/34313650-8819360e-e721-11e7-8541-b7368d43a8f0.png)
![xenia detached_80b0b66e_dec 22 2017 _ 4d53085b halo_ reach _vulkan_ 12_22_2017 2_02_40 pm 2](https://user-images.githubusercontent.com/14243076/34313665-9a2f6822-e721-11e7-8ce8-62caea95c486.png)
Brighter pictures for people with really dark screens.

**Comment by Caboosium** [comment]
You know what should be the background looks like it might be 3d... See the way its leaning to the left on the left side and leaning right close to the right side?

**Comment by Caboosium** [comment]
Here is my log from when that happened.

http://www.mediafire.com/file/64bnhq4c8xs6b36/xenia.log

**Comment by no1dead** [comment]
Well yeah the UI is 3Dish and so is the background I'm pretty sure.

**Comment by Caboosium** [comment]
Was able to recreate it and I got a video. Here is another screen shot while I upload the video.

[ORIGINAL]
![xenia detached_80b0b66e_dec 22 2017 _ 4d53085b halo_ reach _vulkan_ 12_22_2017 2_23_32 pm](https://user-images.githubusercontent.com/14243076/34314004-88ebe83a-e724-11e7-95fc-b103475b64ab.png)

[EDITED]
![xenia detached_80b0b66e_dec 22 2017 _ 4d53085b halo_ reach _vulkan_ 12_22_2017 2_23_32 pm 2](https://user-images.githubusercontent.com/14243076/34314012-98ecfa9e-e724-11e7-921d-39fcf3961ac2.png)

**Comment by Caboosium** [comment]
Last picture was like lines but this one almost looks like symbols. I think I see part of the UNSC symbol on the right side. 

Oh and here is that video: https://gaming.youtube.com/watch?v=p1cYimDkIpo&feature=share

**Comment by WRTuL** [comment]
The latest build of xenia with the commit 8784daf get the game ingame and then crashed https://i.imgur.com/zhI72zu.png Apologies if I reported this issue in the wrong format, still trying to grasp the whole GitHub thing.

**Comment by WRTuL** [comment]
Another 2 images, 1st before it crashes: https://i.imgur.com/hADFaks.jpg 2nd when it crashed https://i.imgur.com/JssPZT0.png

**Comment by Caboosium** [comment]
Looks intresting. What about the main menu still look the same?

**Comment by Caboosium** [comment]
Also is "gpu-indexed-vfetch" an improvement?

**Comment by WRTuL** [comment]
The main menu is still the same when you press any of the buttons to bring up the actual menu the game throws up the error in the screenshots I posted. Roughly 2 or 5 sec after pressing anything when the Carter Picture pops up.

**Comment by WRTuL** [comment]
No idea honestly. From what the tag says, gpu-indexed-vfetch is probably related to vertex data though I might be wrong so don't quote me on that.

**Comment by Caboosium** [comment]
When carter comes up press A and then spam B to get out of the shop. Then spam A again to try to get into campaign. Tell me what happens.

**Comment by WRTuL** [comment]
I'm able to get into the menu but it crashes straight after with the same error. https://i.imgur.com/kBdUklh.png Although when launching the game straight after the Bungie cinematic you can see random textures briefly just before Carter pops up.

**Comment by Caboosium** [comment]
Thanks. I'll look at xenia once I get home.

**Comment by Caboosium** [comment]
With this build: https://ci.appveyor.com/project/benvanik/xenia/build/1.0.1127-master/job/rrig8cklql0mdmny/artifacts

I got the game to do the following twice.
![xenia detached_80b0b66e_dec 22 2017 _ 4d53085b halo_ reach _vulkan_ 12_30_2017 9_12_27 pm](https://user-images.githubusercontent.com/14243076/34459654-a9c1ea32-edaa-11e7-8e76-3f129ad1ffe5.png)

**Comment by Caboosium** [comment]
Still can't get into campaign.

**Comment by WRTuL** [comment]
How would we go about getting the text on the menu to render? I'm familiar with C++ but never worked with Vulkan, I'm willing to help but I just don't know where to start. I'm also curious if it's possible to build a one player build of Xenia in order to test the game.

**Comment by Caboosium** [comment]
Same here. If I could make a one player build I would.

**Comment by Caboosium** [comment]
Has anyone tried connecting 4 controllers? I only have 2 I can use.

**Comment by WRTuL** [comment]
I don't see why you would delete files from the game. The build you linked can easily get into the menu without the need of game files being tampered with.

**Comment by Caboosium** [comment]
I was talking about the background of the game.

**Comment by WRTuL** [comment]
My background is sometimes the same, although weird black lines are coming down sometimes. https://i.imgur.com/RoIOszm.png Here's the screenshot.

**Comment by Caboosium** [comment]
On yours it did not load the background. Maybe some type of overlay now that I think about it...

**Comment by Irixion** [comment]
This game won't be playable any time soon. The image of Carter is the message welcoming new players to Halo Reach. As mentioned above, there are certain texture formats that are not yet implemented. On top of that, there is no way of seeing if or how far the game will go once it's in game. There's just too much missing from the emulator for this title as it stands right now.

**Comment by Caboosium** [comment]
We already knew that.

**Comment by Caboosium** [comment]
Always good to be brought back to reality though.

**Comment by Caboosium** [comment]
Have you ever listened to the main menu music at 2x speed? Choir of ants! xD

**Comment by WRTuL** [comment]
I'm aware that's why I'm offering my help and whatever knowledge I have on the topic, I just don't know where to start.

**Comment by Yottabiter** [comment]
We're getting there step by step.
*whispers* Remember Reach!

**Comment by Caboosium** [comment]
Still can't wait. Has anyone tested reach recently though?

**Comment by WRTuL** [comment]
Unable to download the latest build from appveyor, keep getting a network error. Might be me, no idea though. Last time I tried with a recent build I had the "assertion failed" error.

**Comment by somereallygoodname** [comment]
It's the same.

**Comment by Gordex123** [comment]
Pressed A on the controler multiple times. Came to this menu
![grafik](https://user-images.githubusercontent.com/38857145/39426245-6b13b368-4c7f-11e8-9b48-eca6ba34f85c.png)
![unbenannt](https://user-images.githubusercontent.com/38857145/39426256-7068f328-4c7f-11e8-8542-e7ed8e667a66.PNG)

**Comment by Caboosium** [comment]
Remove the black boxs and I got my new background

**Comment by haloix** [comment]
The game now loads into campaign by using the menu, it starts up the first level cut scene but the audio cuts out and graphical errors. Freezes after cut scene when game play is suppose to start 

![screenshot 51](https://user-images.githubusercontent.com/39768033/40725492-7d747714-641b-11e8-81a2-a0f3b11e155f.png)

Video - https://youtu.be/OFel8ISGv8Y

**Comment by yolarrydabomb** [comment]
![image](https://user-images.githubusercontent.com/13090096/41000261-6efbff1c-68db-11e8-8768-1186911bde03.png)

Firefight now playble https://youtu.be/I3jrb4YyRX8
Credit: dany5639

**Comment by Legi0n94** [comment]
Just curious. What limitations in the code are stopping the proper render of some of these games. i.e. some sort of special drawing method for the textures that only xbox has or something else?

**Comment by Legi0n94** [comment]
Alright, I don't know how dan5639 got his game to run at such a high fps, but I have found a few things.

I wanted to find out what was that one element Xenia was missing cause we are very close to cracking this open. So I decided to run a few tests; I ran Halo Reach. I managed to boot it into Firefight and my frames were hitting a max of 2fps. Continuing with this painstaking fps, I found a way to find textures for the game:

### **Albedo Textures:**
![capture](https://user-images.githubusercontent.com/40076324/43901705-3d23b00e-9c3c-11e8-900e-a2efd792bfd3.PNG)

### **Normal Maps:**
![yeet_normal](https://user-images.githubusercontent.com/40076324/43901782-718e1a28-9c3c-11e8-84d9-adc3cb1db5ff.png)

### **Emissive Maps:**
![yeet_black](https://user-images.githubusercontent.com/40076324/43901835-9488e6de-9c3c-11e8-9991-3988e408d705.png)

### **Depth Maps:**
![yeet_depth](https://user-images.githubusercontent.com/40076324/43901855-a0c1b4da-9c3c-11e8-9e21-488aaf9e5b2b.png)

### ----------------------------------------------------------------------

**So the conclusion I have come to is that Xenia is capable of rendering everything, but for some reason can't seem to render the ambient/environmental lighting or the HDR Maps used in the game**

**Comment by Debiraw** [comment]
I'm sorry i can't help u but pls never give up my dream is to play at this game on my pc im sure u can do it

**Comment by Legi0n94** [comment]
Same here, I've played CE and 2 and I haven't watched any gameplay vids for all the others cause I have been waiting for the time I can finally play for myself and I know we are close - we got the game running and everything loaded in, just a few important tidbits missing and hopefully we can pull this off.

**Comment by Impulsive117** [comment]
Love all you guys and appreciate the work, just made an account to let you know what you're doing is making a difference. I had one question, to play with decent frames as of today, would I need to modify my Xenia or Halo: Reach iso?

**Comment by Xufau** [comment]
You can modify both to increase the fps, I recommend waiting for Xenia to be updated though.

**Comment by Impulsive117** [comment]
Ok. will keep my eyes peeled thanks man.

**Comment by Impulsive117** [comment]
Last one, where can I get a good copy of Reach? I've looked around with no luck :(

**Comment by Impulsive117** [comment]
Yeah I managed to get through the black menus to firefight and achieved 1 frame per 10 seconds using a 1070 + i7 7700hq

**Comment by PotatoAndSickle** [comment]
Update as of commit eb50ebd8 on 29/09/28
**note these images are taken on Nvidia hardware (1070)**
![image](https://user-images.githubusercontent.com/38285436/46264246-cacf1700-c55d-11e8-9b3f-9e8527370bfa.png)
some text is not loading
![image](https://user-images.githubusercontent.com/38285436/46264252-e9cda900-c55d-11e8-8931-c9c946e8bbb7.png)
examples of text that is being pulled
![image](https://user-images.githubusercontent.com/38285436/46264275-21d4ec00-c55e-11e8-8a91-fc72f39093dd.png)
![image](https://user-images.githubusercontent.com/38285436/46264283-43ce6e80-c55e-11e8-9126-80ca1d20ecc0.png)
![image](https://user-images.githubusercontent.com/38285436/46264285-5648a800-c55e-11e8-9c63-1ef25102e6a1.png)
no effects are being rendered
![image](https://user-images.githubusercontent.com/38285436/46264302-8db75480-c55e-11e8-9d22-f2c2891b3b60.png)

overall incredible progress done by triangle and the rest of the team

**Comment by Impulsive117** [comment]
Thank you so much

**Comment by Legi0n94** [comment]
bruh... I knew we were close. Does the campaign boot up normally?

**Comment by yolarrydabomb** [comment]
Also a video https://www.youtube.com/watch?v=WgNjV4J-IUY

**Comment by Legi0n94** [comment]
Well as long as it doesn't crash and burn harder than the Hindenburg, I'm happy with their progress. That being said, I would still love to see it game at a decent 50-60 frames

**Comment by Legi0n94** [comment]
One more thing. If someone knows how dan5639 got the high fps in the previous build, maybe they could use the same trick to try the game with 60 fps and possibly less glitchier textures

**Comment by PotatoAndSickle** [comment]
@Legi0n94 that game was modified also it was not running at 60fps it was 30. 30fps is the maximum framerate the game can run at

**Comment by Legi0n94** [comment]
Oh. I think it just felt very smooth so yeah... But if anyone knows how to modify the game like that, they could try and get it running without the glitchy textures and lagging, I guess.

**Comment by Samg381** [comment]
Looking forward to seeing this progress.

**Comment by PotatoAndSickle** [comment]
### Progress update as of 64d55740/oct 24 2018 
**note using both images are using ROV**
rainbow aliasing is completely gone + tree leaves etc now render correctly as a result 
**Before**
![image](https://user-images.githubusercontent.com/38285436/47477661-1b424780-d872-11e8-99b1-ab1f1ebbc918.png)
**After**
![image](https://user-images.githubusercontent.com/38285436/47477978-73c61480-d873-11e8-8213-c2644325439d.png)

Thanks again to triangle, emoose and gibbed for all of their hard work over theses couple of days

**Comment by wallnutkraken** [comment]
@PotatoAndSickle any idea what the change was and how to reproduce it?

**Comment by PotatoAndSickle** [comment]
@wallnutkraken i am not following the bug i was showing in the image was fixed check the before and after images

**Comment by Samg381** [comment]
Just wanted to say keep up the excellent work. I literally cannot I'm playing Reach on my computer and I'm incredibly impressed at the progress that has been made.

**Comment by Legi0n94** [comment]
So I just tried booting reach on the latest version of Xenia and I am still getting the black menu screen. What's up with that?

**Comment by PotatoAndSickle** [comment]
> So I just tried booting reach on the latest version of Xenia and I am still getting the black menu screen. What's up with that?

download the d3d12 branch not the master branch

**Comment by Legi0n94** [comment]
ah I'll try that

**Comment by Legi0n94** [comment]
That worked. Thanks!

**Comment by Legi0n94** [comment]
So I booted up the career and uh...
![capture](https://user-images.githubusercontent.com/40076324/48921573-6f8a2700-ef05-11e8-8e33-a01047c2b24b.PNG)
I think there are still a few textures glitching out :)

**Comment by Samg381** [comment]
The campaign is the only reason I'm hoping Reach gets fully functional. You don't even make it past the Noble Actual mission, it crashes before you get to the Winter Contingency / Visegrád Relay.


 

    On Thursday, November 22, 2018 3:53 PM, Aradhya Chawla <notifications@github.com> wrote:
 

 So I booted up the career and uh...

I think there are still a few textures glitching out :)—

**Comment by Legi0n94** [comment]
Welp, I just hope the devs keep the builds coming. I really want to see Reach becoming part of the Xenia arsenal when it's finally polished and ready for most of the Xbox games.

**Comment by Nighterlev** [comment]
Reach's campaign gets in-game on one of the missions in the Reach demo.
Gameplay can be seen here:
https://www.youtube.com/watch?v=Q8ZnVAIoQLI&t
![screenshot_12](https://user-images.githubusercontent.com/44956068/49232650-f897d700-f3b9-11e8-8feb-a33503884db0.png)

**Comment by InwardHydra** [comment]
Huh, reminds me of Assassins Creed Unity with the no heads thing, but overall looking good! Anyone have an Idea why the full games has trouble booting story?

**Comment by Nighterlev** [comment]
> 
> 
> Huh, reminds me of Assassins Creed Unity with the no heads thing, but overall looking good! Anyone have an Idea why the full games has trouble booting story?

The full release game can get in story to, but for some odd reason the 1st mission just doesn't want to work.  I wouldn't be surprised if you managed to mod Reach so all missions are available, and this very same mission would probably work just fine on the full release to.

**Comment by Ocman76** [comment]
Hey guys, just learned about Halo Reach running on Xenia and wanted to come express my appreciation, emulating this game on PC has been a dream for years.  The amount of work required to get this even partially working is incredible.

I am wondering if any progress has been made for text in the menus, I currently do not see any text using the d3d12 branch.

In addition I have not yet been able to make it past the first campaign mission cutscene, as the cutscene is running between 3-30 fps and crashes.  I am by no means a coder but I would love to help by providing screenshots/videos of any bugs I am encountering if it helps with development!

My PC Specs:
Windows 10 Pro 64 Bit
AMD R5-1600 (Currently at stock)
AMD RX 570
2X8GB DDR4 3200 (Currently at 2133)

**Comment by nickumtoo225** [comment]
so not even going to pretend that i know any of what was said above the progress and dedication for this incredible and i very much appreciate it! anyways found this little thing in the latest version of Xenia with a stock version of Reach...it would appear that the strange stretching during cutscenes and other things is caused by the camera perspective shift from using vehicles such as the Falcon. Hope that is at least somewhat useful, also if we could figure out a way to do some sort of saving, then it is possible to get save files and have access to other levels in the campaign similar to the workaround for Sonic Unleashed when it gets stuck on the main menu. Anyways just jumping onto the Xenia bandwaggon and glad i am, its an awesome project with incredible people, please keep it up!
![image](https://user-images.githubusercontent.com/45758830/49730751-94390b00-fc36-11e8-9536-e5b5df6c2ded.png)

**Comment by nickumtoo225** [comment]
So just deciding to make a new post for this but i am unable to get past the first building in Winter Contingeny, after hitting the blue objective, the data pad if i recall, i full on sprinted and looked down, and all kinds of silly things but there is no making it out of that building that first introduces night vision as far as i can tell... if anyone has gotten further please let me know! i would like to be able to move fast enough to trigger the cutscene that plays there before the game crashes, just to see what happens. anyways heading off now, once again the distance this game has gone from reading everything from top to bottom is incredible and the team here is amazing!

**Comment by Zyxes** [comment]
Hi i have problem with Halo, When i start campaign after first cutscene i have infinite black screen what should i do?

**Comment by Samg381** [comment]
> Hi i have problem with Halo, When i start campaign after first cutscene i have infinite black screen what should i do?

This is a known issue, and hopefully will be addressed by future Xenia updates.

For me, the audio cuts out at the intro to Noble Actual, where Kat and Carter have the face glitch.
The game then crashes between Noble Actual and the Winter Contingency outro/intro cutscenes.

**Comment by Celvox** [comment]
Where do I actually get the iso so I can play this?

**Comment by Irixion** [comment]
Your Xbox? Rip the game yourself and then point Xenia to the file

**Comment by Celvox** [comment]
> Your Xbox? Rip the game yourself and then point Xenia to the file

Don't I need a disc drive?

**Comment by Irixion** [comment]
If you have the digital version you can copy that over and then use something like Xplorer to get you the raw file.

**Comment by Celvox** [comment]
> Install the game

The reason I want to emulate is because I don't have an xbox to play it on.

**Comment by Irixion** [comment]
Why would you buy a game if you don’t own an Xbox? There’s no way of getting the game if you don’t have a console.

**Comment by Celvox** [comment]
I've had the game since 2012 and found it in my closet after selling my 360 years ago.

**Comment by Celvox** [comment]
But whatever I'll try to find a way. :/

**Comment by DaAwsumPiderman** [comment]
Go to this site: https://apps.win-serv.com/dl/xbox

You'll see a box near the top of the screen about FTP connection. Install FileZilla and connect to that FTP server. You can download literally everything you need from there.

**Comment by Irixion** [comment]
I’d rather not see this project shut down for promoting piracy. Get the game legitimately. @DrChat.

**Comment by Samg381** [comment]
I've had the files from my disk ripped for a while now, and gave up trying to get them onto an ISO.Anyone care to elaborate? Someone mentioned 'Xplorer'? Thanks.
 

    On Thursday, January 31, 2019 6:22 PM, Irixion <notifications@github.com> wrote:
 

 I’d rather not see this project shut down for promoting piracy. Get the game legitimately. @DrChat.—

**Comment by Manoluuu** [comment]
friends please do not abandon the project, this game summarizes all my childhood, happiness and almost life as a child as I lived very alone. I just want to have the game and be able to spend the campaign as many times as necessary. for me and for many more we ask them to be our heroes and not abandon the dreams of many and theirs. a hug.

**Comment by DanJoeBanJoe** [comment]
Dont Worry Brothers I Am Going To test to see if REACH works

**Comment by goodclone** [comment]
I wish to bring to the the threads attention that this is the first game coming to pc on steam.

**Comment by DanJoeBanJoe** [comment]
we know that but we just want it to work for the people who can really run this game on pc but on an emulator once its fixed

**Comment by DanJoeBanJoe** [comment]
so far i am stuck on this screen on reach

**Comment by DanJoeBanJoe** [comment]
![asdasdasdsad](https://user-images.githubusercontent.com/49356309/55917328-01e14d80-5bbd-11e9-9be1-e6a6037fcaa6.PNG)

**Comment by no1dead** [comment]
You have to skip past the cinematics. The game goes a lot farther then that.

**Comment by DanJoeBanJoe** [comment]
yes ok its working now

**Comment by DanJoeBanJoe** [comment]
no audio but cinematic is fine

**Comment by DanJoeBanJoe** [comment]
still the same from before but does not load into mission. Just Black SCREEN

**Comment by InwardHydra** [comment]
As far as I know, Reach has always had trouble loading "Winter Contingency", but it may be just that mission. In the Halo Reach demo, the mission "Long Night of Solance" was able to run, so it's a problem with something the level tries to do.

**Comment by vickyiori** [comment]
Hi All,

First I've to say that the work you people have done is amazing.

I'm facing an odd problem.

I'm using Xenia 13 May 2019 Build.

Whenever I start halo reach, after first cut-scene, I get black screen with white outline.

Can anybody here as what may need to be done to solve this issue?

Appreciated.

Thanks,
Vicky

**Comment by win98and95** [comment]
@vickyiori join our [discord](https://discord.gg/5g93S8H) server and we'll help you out :)

**Comment by matiascode6611** [comment]
hi where can i download halo reach

**Comment by darkquake93** [comment]
Hey guys,

so currently Reach looks pretty good but campaign still isn't playable. The starting cinematic only has sound for the first few seconds still, then cuts out. Graphically though, it's looking good (until Kat appears lol). Then it just shows a black screen, so can't get into actual gameplay..

A Custom Game on the other hand loads fine after about 10 seconds, and plays fairly well with slight stuttering.
![Reach3](https://user-images.githubusercontent.com/8112825/68531422-ee8c9100-0309-11ea-9c4d-b5f879ad72ca.PNG)
![Reach2](https://user-images.githubusercontent.com/8112825/68531424-ee8c9100-0309-11ea-98f1-3a9efd185883.PNG)
![Reach1](https://user-images.githubusercontent.com/8112825/68531425-ee8c9100-0309-11ea-827b-c604eb2821c4.PNG)
![Reach5](https://user-images.githubusercontent.com/8112825/68531427-ef252780-0309-11ea-8dbb-77cf9bb8625a.PNG)
![Reach4](https://user-images.githubusercontent.com/8112825/68531428-ef252780-0309-11ea-89de-8e0a0019c854.PNG)

**Comment by Nighterlev** [comment]
@darkquake93 I know your update is a few months old now, but we've been able to get into actual gameplay of Reach's campaign since 2018.  You have to start the missions up directly, you can't complete the entire game in one sitting at all. 
I did it on the Reach demo, and retail.  Here's me doing it on the Reach demo back in 2018.
https://github.com/xenia-project/game-compatibility/issues/52#issuecomment-442877268

I can easily make more videos of me doing it on just about every mission if you want me to.

**Comment by darkquake93** [comment]
@Nighterlev Sorry for my late reply also :p

Oh right, well I gave up in the end.. now Halo Reach is on PC. I ended up just buying it and playing through that way. Could never get past that first cutscene though on Xenia, any special config that was needed for Reach retail?

**Comment by haloman30** [comment]
Hey - not sure if this is just a fluke or something, but in the latest download of Xenia, Reach doesn't appear to work anymore. The build is at commit 617b17e25 and using the Direct3D 12 renderer.

Halo 3 and ODST run great outside of some minor hitching and some decals not drawing right, but Reach fails to render anything after the intro video.

You can hear the main menu music playing in the background as well as UI sounds, but graphically the only thing visible is the last frame of the intro video that was shown.

Renaming the 'bink' folder to something else in order to disable intro videos takes you to the menus but still with nothing visible other than a black screen.

I used an older version I had laying around to figure out what inputs I needed to do in order to attempt to start up a multiplayer session and get in-game. But that doesn't work in the newer build - you can navigate to the different lobbies, but upon trying to actually start the game, it just plays the error sound - the one that plays if the menu item is disabled. As such, you can't guess your way into a game either - so I don't know if it works any better or worse when it's fully in-game.

For reference, the working build I have that gets Reach to load is 445d7845, from Oct 25 2020.

**Comment by darkquake93** [comment]
> Hey - not sure if this is just a fluke or something, but in the latest download of Xenia, Reach doesn't appear to work anymore. The build is at commit 617b17e25 and using the Direct3D 12 renderer.
> 
> Halo 3 and ODST run great outside of some minor hitching and some decals not drawing right, but Reach fails to render anything after the intro video.
> 
> You can hear the main menu music playing in the background as well as UI sounds, but graphically the only thing visible is the last frame of the intro video that was shown.
> 
> Renaming the 'bink' folder to something else in order to disable intro videos takes you to the menus but still with nothing visible other than a black screen.
> 
> I used an older version I had laying around to figure out what inputs I needed to do in order to attempt to start up a multiplayer session and get in-game. But that doesn't work in the newer build - you can navigate to the different lobbies, but upon trying to actually start the game, it just plays the error sound - the one that plays if the menu item is disabled. As such, you can't guess your way into a game either - so I don't know if it works any better or worse when it's fully in-game.
> 
> For reference, the working build I have that gets Reach to load is 445d7845, from Oct 25 2020.
> 
> Below is the log file from the current Xenia build. [xenia.zip](https://github.com/xenia-project/game-compatibility/files/7875656/xenia.zip)

Hey, thanks for testing but I haven't tried again myself since 2018. I gave in and just purchased the Halo MCC for PC; it doesn't seem worth the time getting this running in Xenia as opposed to just playing the native PC version.

It's all very interesting trying to get these things running but I was keen to play the game really, sounds like certain versions work better for it than others though.

Maybe in the future when it does run smoothly, it'd be cool to do split screen coop on the same machine cause that's the only difference I can think of worth playing compared to the PC version :) Halo 3 seemed to work well with it though!

**Comment by Sowa95** [comment]
Tested on: https://github.com/xenia-project/xenia/commit/f6b5424a9f7daee69ea7ea837b6d4224ea47c368

[xenia.zip](https://github.com/xenia-project/game-compatibility/files/15010185/xenia.zip)

- needs `readback_resolve` to correct brightness.
- some lights are not occluded.

![rr1](https://github.com/xenia-project/game-compatibility/assets/113144725/ee9903e1-0c08-4cc4-98f7-7237b9721161)
![rr2](https://github.com/xenia-project/game-compatibility/assets/113144725/249bb11d-01fa-4b67-8e29-a4ed393c3ae3)

**Comment by starwars1717** [comment]
what are all of the setting for halo reach in the config

**Comment by Mungr3ss** [comment]
this game and halo 4 refuse to load modded maps when the xex patches are used. but for some reason a modded mainmenu.map works fine but any other maps say "players failed to load content"

halo 3 and odst work fine with their xex patches & modded maps. no content errors.
