### ISSUE TITLE
4B4E07D1 - Rumble Roses XX

### ISSUE THREAD

**Issue by Parovozik** [xenia-project/game-compatibility#770]
[Marketplace](https://marketplace.xbox.com/ru-RU/Product/Rumble-Roses-XX/66acd000-77fe-1000-9115-d8024b4e07d1)

Tested on (https://github.com/benvanik/xenia/commit/1e9786eae395ef09de81e82d1c13d6426c7dc6c5)

# Issues:
Some troubles of graphics (morphing of models, blurred image, transparency for some textures), but globally all works
Sound OK. Performance OK. Stable ingame.

# Log:
[RumbleRoses_VK.txt](https://github.com/xenia-project/game-compatibility/files/999813/RumbleRoses_VK.txt)

# Video:
[YouTube_RubleRosesXX_Vulkan](https://www.youtube.com/watch?v=grd0x31ZguM)

# Screenshot(s):
![xenia rumblerosesxx github mp4_snapshot_00 48_ 2017 05 15_02 45 29](https://cloud.githubusercontent.com/assets/19775644/26038780/af85defc-3918-11e7-9031-2e21a1293f40.jpg)
![xenia rumblerosesxx github mp4_snapshot_01 59_ 2017 05 15_02 45 55](https://cloud.githubusercontent.com/assets/19775644/26038782/b1e92f00-3918-11e7-8057-92c6adffacea.jpg)
![xenia rumblerosesxx github mp4_snapshot_02 11_ 2017 05 15_02 46 01](https://cloud.githubusercontent.com/assets/19775644/26038784/b7ec9914-3918-11e7-853b-ecf87e92d363.jpg)

# Specs:
CPU Intel i5-3570K @ 3.6 GHz
GPU GTX 1050ti 4GB
RAM 8GB DDR3 (DC)
Windows 10 x64

# Labels:
gpu-corrupt-drawing
state-gameplay

**Comment by rwchunk** [comment]
### Update
Visuals are fixed.
Tested on d3d12 https://github.com/xenia-project/xenia/commit/45cee3f8710f34c20612401aedb784bb1d41c63c

### Issues:
**(these are minor non-game-breaking issues)**
Freezes for a minute before it can play the opening video
Will freeze for a few minutes on opening tutorial (a video playback)

### Log:
[output.log](https://github.com/xenia-project/game-compatibility/files/3073877/output.log)

### Screenshot:
Screenshot while waiting for the opening.
![freeze](https://user-images.githubusercontent.com/19255865/56048539-5c89bf00-5d0d-11e9-9182-76309a9b4d3c.PNG)
General tests
![001](https://user-images.githubusercontent.com/19255865/56060844-94a0fa00-5d2d-11e9-8701-0557441433b7.PNG)
![002](https://user-images.githubusercontent.com/19255865/56060850-95d22700-5d2d-11e9-911d-55f606ea55d0.PNG)

### Specs:
AMD Ryzen R7 1700X 3.4GHz
GTX1080Ti 11GB
16GB DDR4
Windows 10 x64

### Labels:
state-playable

**Note:**
Using an older version of Windows 10 was getting constant 30-60ms or higher frametime. Not an issue after updating.

**Comment by DMI-1407** [comment]
> 
> ### Update
> 
> Visuals are fixed.
> Tested on d3d12 [xenia-project/xenia@45cee3f](https://github.com/xenia-project/xenia/commit/45cee3f8710f34c20612401aedb784bb1d41c63c)

The issue belongs to Vulkan, for dx12 it might be fixed but related to Vulkan the morphing issue is still present.
(detached/9f789e01/Jun  7 2020)
![grafik](https://user-images.githubusercontent.com/53574099/84943450-a544c100-b0e4-11ea-92a9-09e169b20376.png)

Also it looks like some materials (from models) arent displayed in menu views,
but this morphing issue happens in both, menu views and "ingame".

**Comment by TroudhuK** [comment]
Even if I set the region and language to FR in xenia(-canary).config.toml, the PAL version stays in English. With wx360 I see the multi languages.
![image](https://user-images.githubusercontent.com/11449740/97765905-6a33af00-1b14-11eb-899f-f8c1ca2935c5.png)

**Comment by princessGasmask** [comment]
Crashes at certain points for me. Using DLC outfits crashes the game and Black Belt Demon's entrance seems to 100% crash.

**Comment by princessGasmask** [comment]
Fatal 4 ways always crash for me now as well.

**Comment by tore952** [comment]
i> F8000004 XE_SWAP
G> F8000004 Loaded tiled 1280x720x1 2D k_8_8_8_8 texture with 1 unpacked mip level, base at 0x1D058000 (size 0x00398000), mips at 0x00000000 (size 0x00000000)
i> 00002A9C Context lost; Reset invoked
w> F8000004 Too few processor cores - scheduling will be wonky
i> F8000474 VdSwap(BE5CE200, AE5FFE30, FFBF6008, 4053FBD0, BEEF0001, 4053FB90(FD057000), 4053FB9C(00000006), 4053FBA0(00000000), 4053FB98(00000500), 4053FB94(000002D0))
!> F8000004 **** INDIRECT RINGBUFFER: Failed to execute packet.

Crashes on loading i belive. Not inmenus. If you can load into a match it seems like it'll keep working. INDIRECT RINGBUFFER seems to be a common issue for me.

**Comment by Corsair1992** [comment]
I've attempted running on clean saves and I was still getting crashes. But the save points increasing the crash load sounds about right, cause I can barely load into the game anymore. 

Is this game still a WIP. Anything I can do to help?

**Comment by SS4K** [comment]
unfortunately the game is crashing from the last 9 months builds to this day  , was 90% playable , at the current state it crash at characters selection or at the start of the match

Needs Updating

**Comment by vashdlad** [comment]
I am able to get to the map, but the second I try to start a match, the game crashes at the fight load screen

**Comment by Hawker65** [comment]
From my own experience, New Game seems to be more stable than loading a game.

Most if not all of my crashes occur when loading a character's model or shortly after : changing costumes in character customization, changing color in the character selection screen (or simply the when the character model loads in the selection screen), showing the 2 fighters right before the start of the match (where you can press Y to show the status of the fighters involved), at the start of the match. 

At best, I could play 2 matches in a row, but crashes are very frequent. It unfortunately makes the game hardly playable.

Here is the log of my last crash, it crashed right at the screen where you can show status :
[xenia.log](https://github.com/xenia-project/game-compatibility/files/6907492/xenia.log)

I hope it helps.

**Comment by khanh8609vnz3** [comment]
This game right now will crash a lot on the latest xenia, I recommend download last year version 2020, I alr test it and played with zero crash

Im using Jun 2 2020 Xenia

**Comment by Devilhunter142** [comment]
> This game right now will crash a lot on the latest xenia, I recommend download last year version 2020, I alr test it and played with zero crash
> 
> Im using Jun 2 2020 Xenia

Any idea how to build the 2020 xenia version? I did built by instruction but it's still the latest 2021

**Comment by Wecl98** [comment]
> This game right now will crash a lot on the latest xenia, I recommend download last year version 2020, I alr test it and played with zero crash
> 
> Im using Jun 2 2020 Xenia

After testing the june 2 release for about 5 to 6 hours,playing various modes and settings/characters, I can confirm that i've experienced zero crashes.the only problem that im having right now is that apparently this version of xenia lacks an autosave feature,and to my knowledge there is no manual save option in the game or maybe im doing smt wrong,so i cant rlly make much progress in the campaign and the customization.all that aside,this is the best way to play the game now so thank you @Devilhunter142

**Comment by princessGasmask** [comment]
> > This game right now will crash a lot on the latest xenia, I recommend download last year version 2020, I alr test it and played with zero crash
> > Im using Jun 2 2020 Xenia
> 
> After testing the june 2 release for about 5 to 6 hours,playing various modes and settings/characters, I can confirm that i've experienced zero crashes.the only problem that im having right now is that apparently this version of xenia lacks an autosave feature,and to my knowledge there is no manual save option in the game or maybe im doing smt wrong,so i cant rlly make much progress in the campaign and the customization.all that aside,this is the best way to play the game now so thank you @Devilhunter142

You manual save in the locker room.

**Comment by Wecl98** [comment]
> > > This game right now will crash a lot on the latest xenia, I recommend download last year version 2020, I alr test it and played with zero crash
> > > Im using Jun 2 2020 Xenia
> > 
> > 
> > After testing the june 2 release for about 5 to 6 hours,playing various modes and settings/characters, I can confirm that i've experienced zero crashes.the only problem that im having right now is that apparently this version of xenia lacks an autosave feature,and to my knowledge there is no manual save option in the game or maybe im doing smt wrong,so i cant rlly make much progress in the campaign and the customization.all that aside,this is the best way to play the game now so thank you @Devilhunter142
> 
> You manual save in the locker room.

O shet,thats embarrassing thank you lol

**Comment by Devilhunter142** [comment]
> > This game right now will crash a lot on the latest xenia, I recommend download last year version 2020, I alr test it and played with zero crash
> > Im using Jun 2 2020 Xenia
> 
> After testing the june 2 release for about 5 to 6 hours,playing various modes and settings/characters, I can confirm that i've experienced zero crashes.the only problem that im having right now is that apparently this version of xenia lacks an autosave feature,and to my knowledge there is no manual save option in the game or maybe im doing smt wrong,so i cant rlly make much progress in the campaign and the customization.all that aside,this is the best way to play the game now so thank you @Devilhunter142

Nah. I'm not the one who point that out. Do you know how to build an old june xenia 2020? Because I want to play this game in Japanese but unfortunately everytime I try to built by myself it always the latest version. And there's none JP June 2020 xenia ver

**Comment by Wecl98** [comment]
> > > This game right now will crash a lot on the latest xenia, I recommend download last year version 2020, I alr test it and played with zero crash
> > > Im using Jun 2 2020 Xenia
> > 
> > 
> > After testing the june 2 release for about 5 to 6 hours,playing various modes and settings/characters, I can confirm that i've experienced zero crashes.the only problem that im having right now is that apparently this version of xenia lacks an autosave feature,and to my knowledge there is no manual save option in the game or maybe im doing smt wrong,so i cant rlly make much progress in the campaign and the customization.all that aside,this is the best way to play the game now so thank you @Devilhunter142
> 
> Nah. I'm not the one who point that out. Do you know how to build an old june xenia 2020? Because I want to play this game in Japanese but unfortunately everytime I try to built by myself it always the latest version. And there's none JP June 2020 xenia ver

i got it from here https://xenia.en.uptodown.com/windows/versions

**Comment by Corsair1992** [comment]
> > > > This game right now will crash a lot on the latest xenia, I recommend download last year version 2020, I alr test it and played with zero crash
> > > > Im using Jun 2 2020 Xenia
> > > 
> > > 
> > > After testing the june 2 release for about 5 to 6 hours,playing various modes and settings/characters, I can confirm that i've experienced zero crashes.the only problem that im having right now is that apparently this version of xenia lacks an autosave feature,and to my knowledge there is no manual save option in the game or maybe im doing smt wrong,so i cant rlly make much progress in the campaign and the customization.all that aside,this is the best way to play the game now so thank you @Devilhunter142
> > 
> > 
> > Nah. I'm not the one who point that out. Do you know how to build an old june xenia 2020? Because I want to play this game in Japanese but unfortunately everytime I try to built by myself it always the latest version. And there's none JP June 2020 xenia ver
> 
> i got it from here https://xenia.en.uptodown.com/windows/versions

Just to be clear, you said you got the June 2020 version from the link you posted, but is there a JP version? All the ones on that page said English.

**Comment by princessGasmask** [comment]
> > > > > This game right now will crash a lot on the latest xenia, I recommend download last year version 2020, I alr test it and played with zero crash
> > > > > Im using Jun 2 2020 Xenia
> > > > 
> > > > 
> > > > After testing the june 2 release for about 5 to 6 hours,playing various modes and settings/characters, I can confirm that i've experienced zero crashes.the only problem that im having right now is that apparently this version of xenia lacks an autosave feature,and to my knowledge there is no manual save option in the game or maybe im doing smt wrong,so i cant rlly make much progress in the campaign and the customization.all that aside,this is the best way to play the game now so thank you @Devilhunter142
> > > 
> > > 
> > > Nah. I'm not the one who point that out. Do you know how to build an old june xenia 2020? Because I want to play this game in Japanese but unfortunately everytime I try to built by myself it always the latest version. And there's none JP June 2020 xenia ver
> > 
> > 
> > i got it from here https://xenia.en.uptodown.com/windows/versions
> 
> Just to be clear, you said you got the June 2020 version from the link you posted, but is there a JP version? All the ones on that page said English.

There's no such thing as a "JP version" of this emulator.

**Comment by Devilhunter142** [comment]
> > > > > > This game right now will crash a lot on the latest xenia, I recommend download last year version 2020, I alr test it and played with zero crash
> > > > > > Im using Jun 2 2020 Xenia
> > > > > 
> > > > > 
> > > > > After testing the june 2 release for about 5 to 6 hours,playing various modes and settings/characters, I can confirm that i've experienced zero crashes.the only problem that im having right now is that apparently this version of xenia lacks an autosave feature,and to my knowledge there is no manual save option in the game or maybe im doing smt wrong,so i cant rlly make much progress in the campaign and the customization.all that aside,this is the best way to play the game now so thank you @Devilhunter142
> > > > 
> > > > 
> > > > Nah. I'm not the one who point that out. Do you know how to build an old june xenia 2020? Because I want to play this game in Japanese but unfortunately everytime I try to built by myself it always the latest version. And there's none JP June 2020 xenia ver
> > > 
> > > 
> > > i got it from here https://xenia.en.uptodown.com/windows/versions
> > 
> > 
> > Just to be clear, you said you got the June 2020 version from the link you posted, but is there a JP version? All the ones on that page said English.
> 
> There's no such thing as a "JP version" of this emulator.

I had one. The 2019 version and the latest 2021 JP version I built it myself. But unfortunately both version is unstable to play this game. Only the 2020 version is the most stable but English only. I followed youtube and github how to selfbuild xenia but it's always result the latest one so I ask if anybody who knows how to build the 2020 version

**Comment by Wecl98** [comment]
> > > > > > > This game right now will crash a lot on the latest xenia, I recommend download last year version 2020, I alr test it and played with zero crash
> > > > > > > Im using Jun 2 2020 Xenia
> > > > > > 
> > > > > > 
> > > > > > After testing the june 2 release for about 5 to 6 hours,playing various modes and settings/characters, I can confirm that i've experienced zero crashes.the only problem that im having right now is that apparently this version of xenia lacks an autosave feature,and to my knowledge there is no manual save option in the game or maybe im doing smt wrong,so i cant rlly make much progress in the campaign and the customization.all that aside,this is the best way to play the game now so thank you @Devilhunter142
> > > > > 
> > > > > 
> > > > > Nah. I'm not the one who point that out. Do you know how to build an old june xenia 2020? Because I want to play this game in Japanese but unfortunately everytime I try to built by myself it always the latest version. And there's none JP June 2020 xenia ver
> > > > 
> > > > 
> > > > i got it from here https://xenia.en.uptodown.com/windows/versions
> > > 
> > > 
> > > Just to be clear, you said you got the June 2020 version from the link you posted, but is there a JP version? All the ones on that page said English.
> > 
> > 
> > There's no such thing as a "JP version" of this emulator.
> 
> I had one. The 2019 version and the latest 2021 JP version I built it myself. But unfortunately both version is unstable to play this game. Only the 2020 version is the most stable but English only. I followed youtube and github how to selfbuild xenia but it's always result the latest one so I ask if anybody who knows how to build the 2020 version

I personally dont have any experience in this regard,i'd suggest trying to contacting the original developer or people with some experience in here and or other social media platforms like twitter

**Comment by Corsair1992** [comment]
> > > > > > > > This game right now will crash a lot on the latest xenia, I recommend download last year version 2020, I alr test it and played with zero crash
> > > > > > > > Im using Jun 2 2020 Xenia
> > > > > > > 
> > > > > > > 
> > > > > > > After testing the june 2 release for about 5 to 6 hours,playing various modes and settings/characters, I can confirm that i've experienced zero crashes.the only problem that im having right now is that apparently this version of xenia lacks an autosave feature,and to my knowledge there is no manual save option in the game or maybe im doing smt wrong,so i cant rlly make much progress in the campaign and the customization.all that aside,this is the best way to play the game now so thank you @Devilhunter142
> > > > > > 
> > > > > > 
> > > > > > Nah. I'm not the one who point that out. Do you know how to build an old june xenia 2020? Because I want to play this game in Japanese but unfortunately everytime I try to built by myself it always the latest version. And there's none JP June 2020 xenia ver
> > > > > 
> > > > > 
> > > > > i got it from here https://xenia.en.uptodown.com/windows/versions
> > > > 
> > > > 
> > > > Just to be clear, you said you got the June 2020 version from the link you posted, but is there a JP version? All the ones on that page said English.
> > > 
> > > 
> > > There's no such thing as a "JP version" of this emulator.
> > 
> > 
> > I had one. The 2019 version and the latest 2021 JP version I built it myself. But unfortunately both version is unstable to play this game. Only the 2020 version is the most stable but English only. I followed youtube and github how to selfbuild xenia but it's always result the latest one so I ask if anybody who knows how to build the 2020 version
> 
> I personally dont have any experience in this regard,i'd suggest trying to contacting the original developer or people with some experience in here and or other social media platforms like twitter

I also dont have any experience in this. Barely any experience in coding. I dont know what makes a Xenia exe JP or EN. But if there is something I can do, manpower wise, let me know! Am super interested to start playing again after so many crashes, and if I could get my hands on a JP version I'd be extremely happy.

**Comment by Devilhunter142** [comment]
> > > > > > > > > This game right now will crash a lot on the latest xenia, I recommend download last year version 2020, I alr test it and played with zero crash
> > > > > > > > > Im using Jun 2 2020 Xenia
> > > > > > > > 
> > > > > > > > 
> > > > > > > > After testing the june 2 release for about 5 to 6 hours,playing various modes and settings/characters, I can confirm that i've experienced zero crashes.the only problem that im having right now is that apparently this version of xenia lacks an autosave feature,and to my knowledge there is no manual save option in the game or maybe im doing smt wrong,so i cant rlly make much progress in the campaign and the customization.all that aside,this is the best way to play the game now so thank you @Devilhunter142
> > > > > > > 
> > > > > > > 
> > > > > > > Nah. I'm not the one who point that out. Do you know how to build an old june xenia 2020? Because I want to play this game in Japanese but unfortunately everytime I try to built by myself it always the latest version. And there's none JP June 2020 xenia ver
> > > > > > 
> > > > > > 
> > > > > > i got it from here https://xenia.en.uptodown.com/windows/versions
> > > > > 
> > > > > 
> > > > > Just to be clear, you said you got the June 2020 version from the link you posted, but is there a JP version? All the ones on that page said English.
> > > > 
> > > > 
> > > > There's no such thing as a "JP version" of this emulator.
> > > 
> > > 
> > > I had one. The 2019 version and the latest 2021 JP version I built it myself. But unfortunately both version is unstable to play this game. Only the 2020 version is the most stable but English only. I followed youtube and github how to selfbuild xenia but it's always result the latest one so I ask if anybody who knows how to build the 2020 version
> > 
> > 
> > I personally dont have any experience in this regard,i'd suggest trying to contacting the original developer or people with some experience in here and or other social media platforms like twitter
> 
> I also dont have any experience in this. Barely any experience in coding. I dont know what makes a Xenia exe JP or EN. But if there is something I can do, manpower wise, let me know! Am super interested to start playing again after so many crashes, and if I could get my hands on a JP version I'd be extremely happy.

Here's the whole step how to build Xenia 
https://www.youtube.com/watch?v=Xz9lV3RBwPM

And of course you need a Japanese iso version of this game to work
## Install the latest Python 3.x and Git.
## Install Visual Studio Community 2017 (enable "Desktop Develepment with C++" option in the installer).

> git clone https://github.com/xenia-project/xenia.git
> cd xenia
> xb setup
> xb pull
> git checkout d3d12     ## because RRXX works only with d3d12 branch
> git pull               ## update code to the latest
> xb devenv    ## Visual Studio should be launched

## Right click the solution and execute Retarget Solution (screenshot attached), to match project's SDK version to your local one.
## Now it's the time to edit xam_info.cc. and change everything language related to Japanese
## Build the solution and have fun.

**Comment by Rayuzx** [comment]
January 24, 2022 build:

Runs full speed on DX12, but often crashes. Considerable slowdown and worse graphics on Vulkan, but so far no crashing.

Would love to share log, but it's 712MB

**Comment by LukeL6** [comment]
> > This game right now will crash a lot on the latest xenia, I recommend download last year version 2020, I alr test it and played with zero crash
> > Im using Jun 2 2020 Xenia
> 
> After testing the june 2 release for about 5 to 6 hours,playing various modes and settings/characters, I can confirm that i've experienced zero crashes.the only problem that im having right now is that apparently this version of xenia lacks an autosave feature,and to my knowledge there is no manual save option in the game or maybe im doing smt wrong,so i cant rlly make much progress in the campaign and the customization.all that aside,this is the best way to play the game now so thank you @Devilhunter142

Hi, I tried running the game in 2020 June's release and it is almost no crashing. Yet, when I use character's killer move, the game just stopped at a white frame. And then I have delete the game's caches and shaders, otherwise it will not run.

**Comment by has207** [comment]
Very frequent crashes on dx12 but runs pretty well on Vulkan for me on rtx2060, full speed and no noticeable visual issues. There are still some crashes on Vulkan as well but they are very infrequent so the game feels pretty playable as long as you save often.

**Comment by swanmonkey21** [comment]
Hi guys, im playing rrxx on the jun 2nd 2020 version and im trying to find a way to play with a ps4 controller.

**Comment by Wecl98** [comment]
> Hi guys, im playing rrxx on the jun 2nd 2020 version and im trying to find a way to play with a ps4 controller.

Hey, You can either use DS4Windows or have steam open in the background while the controller is plugged in

**Comment by Devilhunter142** [comment]
> 

Well. With the latest xenia. You can change CPU from D3DX12 to Vulkan and you're good to go. No more crash

**Comment by Corsair1992** [comment]
I saw this post came alive sorta- was wondering if anyone knows, or can point me in the direction of how to get my RRXX in Japanese. Supposedly a JPN rom isn't enough, and need to have a setting in the xbox emu that says "I'm a JPN unit" but idk how to do that.

Thank you :3 I hope this game lives forever.

**Comment by Silanda** [comment]
Unstable in D3D12, but runs well in Vulkan.

The only obvious issue I've noticed so far are incorrect polygons coming from the hair of the two front dancers in Superstar Reiko's entrance.

**Comment by dantekazama** [comment]
been tested on d3dx12 it is still crash randomly...
Hope we get new update for this ... 
because DX12 is looks good...

**Comment by Muzkur** [comment]
Trying it on Batocera V39. The game runs smooth but in the menus it keeps very, very fast.

Specs:
Ryzen 2700x, RTX 3060, 32 GB Ram, Batocera V39 (Wine)
