### ISSUE TITLE
454107DC - Burnout Revenge

### ISSUE THREAD

**Issue by tetration** [xenia-project/game-compatibility#914]
Tested on https://github.com/xenia-project/xenia/commit/6209c4a9315f38136825c5eb20b54c70891cb780

# Issues:
Introduction is shown, menus are working correctly but as soon as the game has to render something on its 3D Engine, such as vehicle selection or when the game loads you in a race track only a black screen with the HUD are visible nothing else, it's all a black screen basically. Nevertheless you can still hear the sound of your car´s engine and your car crashing but nothing is shown, which means the game is working but the emulator is probably having some kind of trouble to render.

Other observations: 

- Minor Audio issue: Ingame music is not playing It looks like EA TRAX is not working properly, since no music can be heard during gameplay, car selection, loading screens or menu. However the rest of the audio is perfectly fine and working.
- After I leave the game running for a while with its corrupt graphics I am prompted with a message from Xenia stating: `Xenia error: Graphics device lost (probably due to an internal error)` and then Xenia closes itself as soon as I click ok on the error message.

# Log:
[xenia - Copia.log](https://github.com/xenia-project/game-compatibility/files/1958011/xenia.-.Copia.log)

# Screenshot(s):
![burnout_revenge_xenia](https://user-images.githubusercontent.com/2152854/39399655-284fceb4-4af8-11e8-9718-e5f47c787ec6.png)

# Labels:
gpu-corrupt-drawing

**Comment by Alucardye** [comment]
Now we can get something on DirectX 12, I was using the latest build "1.0.28-d3d12". The movies are completely broken using the Dx12 build.

![desktop screenshot 2018 09 23 - 20 46 01 34](https://user-images.githubusercontent.com/43516180/45932476-97482780-bf74-11e8-9d41-3361b2bd2cbf.png)

![desktop screenshot 2018 09 23 - 20 46 40 62](https://user-images.githubusercontent.com/43516180/45932466-4afce780-bf74-11e8-87b4-6586f9f59383.png)

**Comment by Alucardye** [comment]
Huge improvement using the build "1.0.1404-d3d12"

![desktop screenshot 2018 09 27 - 10 51 17 24](https://user-images.githubusercontent.com/43516180/46138384-ac0e0f00-c243-11e8-9062-cd3fef73a154.png)
and
![desktop screenshot 2018 09 27 - 10 51 51 40](https://user-images.githubusercontent.com/43516180/46138418-c2b46600-c243-11e8-8023-e076387111e4.png)

**Comment by tetration** [comment]
Huge improvements on Xenia D3D12 build [bb53d722](https://github.com/xenia-project/xenia/commit/bb53d722f971c8b8d3d670a0c4a99d9f16e7e0dd)


Before this build the ingame HUD that shows your speed, rating and how much turbo you have left would be cut in half or would not be visible at all. Now the menu appears 100%

![image](https://user-images.githubusercontent.com/2152854/49388134-851ffd80-f70a-11e8-94cc-00d574b7f413.png)

**Comment by GUILLERMOVALI** [comment]
gracias

**Comment by insaneninja117** [comment]
Burnout Revenge uses WMA for the EA-Trax songs (specifically WMA 9.1), these are exactly the same encodes as used for the original Xbox version of the game. While I'm not aware of any other 360 games using WMA instead of XMA, there may be other cross-gen era games that do (NFS: Most Wanted being the most likely example)

**Comment by lastclass74** [comment]
yellow tint .. ;( and videos lag and pauses for 5-10 sec .. will this ever be fixed ???
i love this game but in yellow its not that fun ;)

**Comment by Margen67** [comment]
@lastclass74 This issue tracker is for reporting game compatibility with xenia, not begging for them to be fixed.

**Comment by illusion98** [comment]
Yellow tint fixed in https://github.com/xenia-project/xenia/commit/4731ae026b37491c0b49ff9411f035e347028eb8
![ ](https://cdn.discordapp.com/attachments/309008096800276490/613242372482007040/unknown.png)
![ ](https://cdn.discordapp.com/attachments/309008096800276490/613243625840574484/unknown.png)

**Comment by lastclass74** [comment]
Thx great work .. videos still hangs for 2-4 sec .. but works...

**Comment by tommitytom** [comment]
Game seems to run fine, though as mentioned in the original issue, I get this within the first couple of minutes of racing:
![image](https://user-images.githubusercontent.com/1239670/66884468-04fe4000-f01d-11e9-8940-b503e36f1564.png)

**Comment by tommitytom** [comment]
So I upgraded my GPU (from GTX 760 to RTX 2080S) and no longer get that error.  Also with the latest version the videos no longer stutter.

**Comment by xmat123x** [comment]
I've played the game for 20 hours now without a single game breaking glitch and very few graphical inaccuracies. A couple of observations.

1. Disabling vsync will uncap the framerate but in-game timers will speed up making some timed events impossible
2. When wrecking your car the framerate will sometimes drop to ~15fps when viewing the crash cam, it recovers fully when you're sent back into the race
3.  Certain models / geometry like your car or buildings sometimes have blur or doubled up afterimages around them, it might be intended behavior to provide a sense of speed but it feels amplified with "d3d12_resolution_scale = 2"  enabled
4.  The framerate bounces between 57 to 64 even with vsync on
5.  As posted above the soundtrack doesn't work
6.  The DLC packs don't get picked up by xenia

That's it, even factoring all of these minor issues the game is fully playable and extremely enjoyable. It really should be bumped up to "playable" status.

**Comment by Nighterlev** [comment]
@xmat123x Issues like sound not playing and DLC packs not being picked up doesn't qualify as a state-playable label.  It has to work perfectly from what I know, otherwise it's state-gameplay.

**Comment by Star1-618** [comment]
Runs well on my GTX 1080 Max-Q (ROG Zephyrus GX501GI laptop), albeit except for absence of music tracks when racing in-game as mentioned above.

**Comment by Bostonjunk** [comment]
Doesn't play for me. It can get to menus but as soon as it would do any actual 3D rendering, the game freezes and Xenia just exits without an error.
The log file does not give any clues either.

**Comment by jamesssun** [comment]
Hello. I checked Burnout Revenge on the latest version of the program. Works reasonably well, but there are two main problems. The most important of them is that there is still COMPLETELY no music in the main menu and in races. All other sound, as well as music in the videos and on the start screen is present. Secondly, there are unpleasant drops in performance in races with a large number of cars, and especially in traffic attack mode.

**Comment by jamesssun** [comment]
I downloaded the latest version of the program again and checked the game. The performance feels worse, there is still no music in the game, but, as it seems to me, there are banners showing the artist and the name of the track - it seems like they weren't there before.

**Comment by Star1-618** [comment]
It's August 2022 and still no music tracks in game. The in game music helped make this game something special and created a fantastic atmosphere. This is by far one of the top Xbox 360 games and a fix to get the music working can't come soon enough!

**Comment by jamesssun** [comment]
> It's August 2022 and still no music tracks in game. The in game music helped make this game something special and created a fantastic atmosphere. This is by far one of the top Xbox 360 games and a fix to get the music working can't come soon enough!

I confirm. It's a pity that you still can't enjoy the game's soundtrack. I would like to note that the performance of the game has become better, but still does not reach the "good" level yet. FPS often sags to non-gaming levels. And this is on an eight-core processor and 3080Ti.

**Comment by BruceLeeFan88** [comment]
> > It's August 2022 and still no music tracks in game. The in game music helped make this game something special and created a fantastic atmosphere. This is by far one of the top Xbox 360 games and a fix to get the music working can't come soon enough!
> 
> I confirm. It's a pity that you still can't enjoy the game's soundtrack. I would like to note that the performance of the game has become better, but still does not reach the "good" level yet. FPS often sags to non-gaming levels. And this is on an eight-core processor and 3080Ti.

I just played it using a i7 6700HQ with a 6GB GTX 1060 and 16GB of ram on the most recent Canary build and it flew. Seems performance has been vastly improved.

**Comment by skpManiac** [comment]
Also running this now in 2023 - Happy new Year everyone :) 
The game is flawless apart from the music. The only solution I have is to play the audio as a playlist in MPCE in the background (Audio files are in the EATRAX folder)
Spec is 11th Gen I9, 3080Ti, 64Gb Ram etc....

Fingers crossed that this can be addresses :)

**Comment by Skyll77** [comment]
![Screenshot 2023-01-13 144100](https://user-images.githubusercontent.com/26650000/212232146-b2470e72-9928-46f7-b106-6ab7c621e2cc.png)

The DLC does work, you need to 100% the game to be able to unlock them though. I found a complete [save file](https://www.speedrun.com/resourceasset/l4okc) online and converted through [Modio 5](https://www.softpedia.com/get/System/File-Management/Modio.shtml) to test to see if the DLC works and I can confirm it does indeed work. If you want to test it out for yourself I have compiled the files neatly and you can find them [here](https://drive.google.com/drive/folders/1pbzbXbymcWnl3S0mZdz9r11eGFYiqDVF?usp=share_link) just drag and drop into your content folder of xenia [(documents\xenia\content)], and load player profile 2 or 3 for 100% completion. If you want to manually install the dlc just get them from [here](https://mega.nz/file/ZWAXXDYY#oZw1oZCjelI4qxemXLBFm2t22ZPLOGHcXW6uJbc7Gl8) and make sure the folder 00000002 is in the game folder (454107DC) inside the content folder (documents\xenia\content\454107DC) and create 7 new folders and drag each file and compartmentalize each file into each folder. Copy the file name in each folder and rename the folder corresponding to the files name inside that folder, you can then complete the game and unlock the dlc and play it that way if you wish.

**Comment by Antifreeze44** [comment]
Works Very good on my computer, 3060 12GB, Ryzen 7 5800x, 32GB DDR4 ram 3400mt/s. 
The music does not play like everyone else, but the frame rates are very very good. and 99% fps stays at 56 for me. with 60fps being their the most of the time.  I was thrilled to play this game again in such good quality. once the music issue is resolved this will be perfect emulation imo.

**Comment by KerrWasHere** [comment]
Where can we locate this rom? I own the disc and don’t feel like extracting it

**Comment by CryptidWubz** [comment]
Runs perfectly fine for me, but there's a problem with revenge when you get near misses or boost a popping sound can be heard. Would we be able to fix this?

https://github.com/xenia-project/game-compatibility/assets/91925949/0603e531-bbbf-4bc2-a4ab-e05edb2604d3

**Comment by VFansss** [comment]
> ![Screenshot 2023-01-13 144100](https://user-images.githubusercontent.com/26650000/212232146-b2470e72-9928-46f7-b106-6ab7c621e2cc.png)
> 
> Update: I have made a [folder](https://www.mediafire.com/file/mzhzn8ee9kd17kf/content.zip/file) that has the DLC + Kiosk Cars and a save file that contains three player file slots all titled "RenameMe" (you can load the profile and then go to "driver details" select "player file" then select "save player file" and rename "RenameMe" to whatever you like. When you go to the yellow events (minus burning lap) it will say 3/88 cars unlocked instead of 3/78. This means the DLC and Kiosk Cars are recognised in the player files. Just download and extract the folder and open the "content folder" that you just extracted, inside there you will find another "content" folder, just drag and drop that into Documents\Xenia and if a message pops up, click "replace the files in the destination" open up Xenia and boot up Burnout Revenge and enjoy playing and earning the DLC and Kiosk Cars.

I've uploaded "[content.zip](https://github.com/xenia-project/game-compatibility/files/15263700/content.zip)" directly into this thread, so it will no go lost in time and space

**Comment by Margen67** [comment]
Xenia Canary issue: https://github.com/xenia-canary/game-compatibility/issues/31

**Comment by skynettx** [comment]
Music playback works in https://github.com/xenia-canary/xenia-canary/commit/764f230dd9883bfb63e3aea7642aac26f010e1bb

**Comment by Margen67** [comment]
@skynettx Xenia Canary discussion belongs in the issue linked above.
